import {
  PatientCase,
  PortalUser,
  AccreditationProfile,
  ConsentTextVersion,
  VisaChecklistRule,
  RefundCancellationRule,
  SlaThreshold,
  SecurityMfaLog,
  HospitalPayoutBatch,
  QueueRoutingRule,
} from "@/types/portal";

export const MOCK_PORTAL_USERS: PortalUser[] = [
  {
    id: "user_patient_tariq",
    name: "Tariq Al-Mansoor",
    email: "tariq.mansoor@alnoor.ae",
    role: "patient",
    patientId: "PT-2026-089412",
    country: "United Arab Emirates",
    phone: "+971 50 123 4567",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    mfaEnforced: false,
    isActive: true,
  },
  {
    id: "user_patient_robert",
    name: "Robert Vance",
    email: "robert.vance@gmail.com",
    role: "patient",
    patientId: "PT-2026-089412",
    country: "United States",
    phone: "+1 (555) 234-8921",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    mfaEnforced: false,
    isActive: true,
  },
  {
    id: "user_patient_elena",
    name: "Elena Rostova",
    email: "elena.rostova@gmail.com",
    role: "patient",
    patientId: "PT-2026-009104",
    country: "United Kingdom",
    phone: "+44 7700 900142",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    mfaEnforced: false,
    isActive: true,
  },
  {
    id: "user_cs_ananya",
    name: "Ananya Sharma",
    email: "ananya.sharma@vedaracare.com",
    role: "customer_support",
    assignedQueues: ["Transplant_Tier1", "MENA_Arabic_Desk", "Executive_VIP_Queue"],
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    phone: "+91 98101 88412",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_cs_aisha",
    name: "Aisha Khan",
    email: "aisha.khan@vedaracare.com",
    role: "customer_support",
    assignedQueues: ["Cardiology_Tier1", "Oncology_EMEA", "Orthopedics_MENA", "General_Global"],
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    phone: "+91 98101 23456",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_doctor_gupta",
    name: "Dr. Subhash Gupta",
    email: "dr.subhash.gupta@medanta.org",
    role: "hospital_doctor",
    hospitalId: "hosp_medanta",
    doctorId: "doc_gupta",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
    phone: "+91 124 414 1414",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_cs_carlos",
    name: "Carlos Mendez",
    email: "carlos.mendez@vedaracare.com",
    role: "customer_support",
    assignedQueues: ["Americas_Intake", "Orthopedics_MENA", "General_Global"],
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (305) 555-0199",
    country: "United States",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_cs_fatima",
    name: "Fatima Al-Sayed",
    email: "fatima.sayed@vedaracare.com",
    role: "customer_support",
    assignedQueues: ["MENA_Arabic_Desk", "Oncology_EMEA", "Executive_VIP_Queue"],
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    phone: "+971 4 399 2200",
    country: "United Arab Emirates",
    mfaEnforced: false,
    isActive: true,
  },
  {
    id: "user_doctor_trehan",
    name: "Dr. Naresh Trehan",
    email: "dr.trehan@medanta.org",
    role: "hospital_doctor",
    hospitalId: "hosp_medanta",
    doctorId: "doc_trehan",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
    phone: "+91 124 414 1414",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_doctor_seth",
    name: "Dr. Ashok Seth",
    email: "dr.ashok.seth@fortis.org",
    role: "hospital_doctor",
    hospitalId: "hosp_fortis",
    doctorId: "doc_seth",
    avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80",
    phone: "+91 11 4277 6222",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_doctor_prathap",
    name: "Dr. Prathap C. Reddy",
    email: "dr.prathap@apollo.org",
    role: "hospital_doctor",
    hospitalId: "hosp_apollo",
    doctorId: "doc_prathap",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80",
    phone: "+91 44 2829 0200",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_finance_david",
    name: "David Miller",
    email: "finance@vedaracare.com",
    role: "finance_accounts",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    phone: "+44 20 7946 0991",
    country: "United Kingdom",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_finance_sarah",
    name: "Sarah Jenkins",
    email: "sarah.jenkins@vedaracare.com",
    role: "finance_accounts",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (212) 555-0144",
    country: "United States",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_admin_rajesh",
    name: "Rajesh Verma",
    email: "admin@vedaracare.com",
    role: "super_admin",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    phone: "+91 98110 99887",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
];

// ─── Accreditation Profiles ───────────────────────────────────────────────────
export const MOCK_ACCREDITATION_PROFILES: AccreditationProfile[] = [
  {
    hospitalId: "hosp_medanta",
    hospitalName: "Medanta – The Medicity",
    jciStatus: "active",
    jciExpiry: "2027-03-15",
    jciDocumentUrl: "#",
    nabhStatus: "active",
    nabhExpiry: "2026-11-30",
    nabhDocumentUrl: "#",
    lastAuditedAt: "2025-10-12",
    country: "India",
    city: "Gurugram",
    specialties: ["Cardiac Surgery", "Oncology", "Neurology", "Transplant"],
  },
  {
    hospitalId: "hosp_apollo",
    hospitalName: "Apollo Hospitals",
    jciStatus: "active",
    jciExpiry: "2026-08-20",
    jciDocumentUrl: "#",
    nabhStatus: "active",
    nabhExpiry: "2027-01-10",
    nabhDocumentUrl: "#",
    lastAuditedAt: "2025-07-04",
    country: "India",
    city: "Chennai",
    specialties: ["Orthopedics", "Oncology", "Cardiology", "Transplant"],
  },
  {
    hospitalId: "hosp_fortis",
    hospitalName: "Fortis Memorial Research Institute",
    jciStatus: "pending_renewal",
    jciExpiry: "2026-09-30",
    jciDocumentUrl: "#",
    nabhStatus: "active",
    nabhExpiry: "2027-05-22",
    nabhDocumentUrl: "#",
    lastAuditedAt: "2025-08-01",
    country: "India",
    city: "Gurugram",
    specialties: ["Radiosurgery", "Oncology", "Neurosurgery"],
  },
];

// ─── Consent Text Versions ────────────────────────────────────────────────────
export const MOCK_CONSENT_TEXT_VERSIONS: ConsentTextVersion[] = [
  {
    id: "ctv_01",
    consentType: "privacy_data_processing",
    country: "United Kingdom",
    version: "v2.4",
    text: "Full GDPR-compliant data processing consent text for UK patients...",
    uploadedAt: "2026-01-15T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
  {
    id: "ctv_02",
    consentType: "privacy_data_processing",
    country: "United Arab Emirates",
    version: "v2.3",
    text: "GCC-compliant data processing consent for UAE patients...",
    uploadedAt: "2026-02-01T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
  {
    id: "ctv_03",
    consentType: "hospital_document_sharing",
    country: "Global",
    version: "v1.8",
    text: "Hospital document sharing consent text — global default...",
    uploadedAt: "2026-01-20T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
  {
    id: "ctv_04",
    consentType: "tele_consultation_terms",
    country: "Global",
    version: "v2.0",
    text: "Tele-consultation terms and scope limitations...",
    uploadedAt: "2026-03-10T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
  {
    id: "ctv_05",
    consentType: "payment_staged_terms",
    country: "Global",
    version: "v1.2",
    text: "Staged payment and escrow terms and conditions...",
    uploadedAt: "2026-01-15T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
];

// ─── Visa Checklist Rules ─────────────────────────────────────────────────────
export const MOCK_VISA_CHECKLIST_RULES: VisaChecklistRule[] = [
  {
    id: "vr_uk",
    patientHomeCountry: "United Kingdom",
    requiredDocuments: [
      { name: "Passport (min 6 months validity)", mandatory: true },
      { name: "Hospital invitation letter (M-Visa)", mandatory: true },
      { name: "Bank statement (last 3 months)", mandatory: true },
      { name: "Travel insurance proof", mandatory: false, note: "Recommended" },
    ],
    lastUpdatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "vr_uae",
    patientHomeCountry: "United Arab Emirates",
    requiredDocuments: [
      { name: "Passport (min 6 months validity)", mandatory: true },
      { name: "Hospital invitation letter (M-Visa)", mandatory: true },
      { name: "Emirates ID copy", mandatory: true },
    ],
    lastUpdatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "vr_ke",
    patientHomeCountry: "Kenya",
    requiredDocuments: [
      { name: "Passport (min 6 months validity)", mandatory: true },
      { name: "Hospital invitation letter (M-Visa)", mandatory: true },
      { name: "Medical diagnosis letter from home doctor", mandatory: true },
      { name: "Bank statement (last 6 months)", mandatory: true },
    ],
    lastUpdatedAt: "2026-06-01T00:00:00Z",
  },
];

// ─── Refund / Cancellation Rules ──────────────────────────────────────────────
export const MOCK_REFUND_RULES: RefundCancellationRule[] = [
  {
    id: "rr_deposit_default",
    paymentStage: "deposit",
    description: "Deposit refund — default",
    refundPercentage: 100,
    conditions: "Fully refundable minus $150 processing fee if visa is denied (official embassy proof required). Non-refundable once visa submitted.",
    lastUpdatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "rr_advance_default",
    paymentStage: "advance",
    description: "Advance refund — default",
    refundPercentage: 90,
    conditions: "90% refundable if cancelled more than 72 hours before planned departure. 50% refundable within 72 hours. Non-refundable after hospital admission.",
    lastUpdatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "rr_final_default",
    paymentStage: "final",
    description: "Final payment refund — default",
    refundPercentage: 0,
    conditions: "Non-refundable once procedure commenced. Disputed amounts subject to reconciliation review.",
    lastUpdatedAt: "2026-01-15T00:00:00Z",
  },
];

// ─── SLA Thresholds ───────────────────────────────────────────────────────────
export const MOCK_SLA_THRESHOLDS: SlaThreshold[] = [
  { market: "UK / EU", tier1Minutes: 45, tier2Minutes: 120, escalationMinutes: 240 },
  { market: "GCC / MENA", tier1Minutes: 30, tier2Minutes: 90, escalationMinutes: 180 },
  { market: "Africa / APAC", tier1Minutes: 60, tier2Minutes: 150, escalationMinutes: 300 },
  { market: "North America", tier1Minutes: 45, tier2Minutes: 120, escalationMinutes: 240 },
];

// ─── Patient Cases ────────────────────────────────────────────────────────────
export const INITIAL_PATIENT_CASES: PatientCase[] = [
  {
    id: "PT-2026-004819",
    patientName: "Eleanor Ruth Whitfield",
    patientEmail: "eleanor.whitfield@nhs-waitlist.co.uk",
    patientPhone: "+44 7700 912845",
    patientCountry: "United Kingdom",
    preferredLanguage: "English",
    treatmentCategory: "Cardiac CABG Bypass Surgery",
    preferredContactTime: "09:00 - 13:00 GMT",
    entryPath: "hospital_referred",
    referredHospitalId: "hosp_medanta",
    assignedHospitalId: "hosp_medanta",
    assignedDoctorId: "doc_trehan",
    assignedQueue: "Cardiology_Tier1",
    assignedCoordinatorName: "Aisha Khan",
    lastContactAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    slaTargetMinutes: 30,
    slaExpiresAt: new Date(Date.now() + 12 * 60 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "mercy_gen_nhs_waitlist",
    utmMedium: "nhs_fasttrack_referral",
    utmCampaign: "cardiac_bypass_uk",

    stage: "lead",
    caseDecisionStatus: "pending_review",

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Severe triple vessel coronary artery disease with critical LAD stenosis (>90%). 14-month NHS waitlist backlog with increasing angina and dyspnea on minimal exertion.",
      diagnosis: "Severe Coronary Artery Disease (CAD) - Triple Vessel Disease with critical Left Anterior Descending (LAD) and Circumflex stenosis.",
      recommendedProcedure: "Coronary Artery Bypass Graft (CABG x 3) with Left Internal Mammary Artery (LIMA) to LAD bypass.",
      pastMedicalHistory: "Hypertension, Hyperlipidemia, Ex-smoker (quit 2021). No prior cardiac interventions.",
      allergies: ["Penicillin"],
    },

    stageHistory: [
      {
        id: "sh_el_01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
        changedByName: "Mercy Gen / NHS Backlog Triage",
        changedByRole: "public",
      },
    ],

    csNotes: [
      {
        id: "note_el_01",
        text: "NHS backlog referral. Critical LAD stenosis >90%. Patient seeking private surgery in Delhi within 10 days. Tele-consult requested with Dr. Naresh Trehan.",
        createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
    ],

    documents: [
      {
        id: "doc_coronary_angio",
        title: "Coronary_Angiography_Report_MercyGen.pdf",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "🟢 Reviewed — Triple vessel disease with 95% proximal LAD lesion documented.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "Coronary_Angiography_Report_MercyGen.pdf",
            fileSize: "8.6 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
            uploadedBy: "Mercy General Hospital",
          },
        ],
      },
      {
        id: "doc_cardiac_echo",
        title: "Transthoracic_Echocardiogram_2026.pdf",
        category: "medical_report",
        status: "reviewed",
        csFeedback: "🟢 Reviewed — LVEF 50%, mild anterior hypokinesia.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "Transthoracic_Echocardiogram_2026.pdf",
            fileSize: "3.2 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
            uploadedBy: "Mercy General Hospital",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_eleanor",
        consentType: "privacy_data_processing",
        title: "UK GDPR & Medical Cross-Border Data Processing",
        description: "Patient granted permission for Medanta Heart Institute to review NHS cardiology files.",
        agreed: true,
        timestamp: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
        ipAddress: "86.14.92.110 (London, UK)",
        version: "v2.4",
        digitalSignature: "Eleanor Ruth Whitfield",
      },
    ],

    consultation: {
      id: "tele_trehan_eleanor",
      scheduledAt: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
      durationMinutes: 30,
      doctorName: "Dr. Naresh Trehan",
      doctorSpecialty: "Chairman & Chief Cardiovascular Surgeon",
      doctorHospital: "Medanta – The Medicity, Delhi NCR",
      doctorAvatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
      meetingLink: "https://vedaracare.health/teleconsult/ved-live-4819",
      status: "scheduled",
      outcome: "pending",
      outcomeNotes: "Urgent CABG assessment. Coronary angio DICOM verified.",
      recordingEnabled: false,
    },

    messages: [
      {
        id: "msg_el_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Hello Eleanor! We received your NHS cardiology referral from Mercy Gen. Dr. Naresh Trehan's cardiac surgical team is reviewing your angiogram now.",
        timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        isRead: true,
      },
    ],
    payments: [],
    recoveryCheckIns: [],
    auditLogs: [
      {
        id: "aud_el_01",
        caseId: "PT-2026-004819",
        action: "LEAD_CREATED",
        actorName: "Mercy Gen NHS Backlog",
        actorRole: "public",
        timestamp: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
        details: "Urgent Cardiac lead generated from UK. SLA: 30 min.",
        ipAddress: "86.14.92.110",
      },
    ],
    refundRequests: [],
  },

  {
    id: "PT-2026-089412",
    patientName: "Tariq Al-Mansoor",
    patientEmail: "tariq.mansoor@alnoor.ae",
    patientPhone: "+971 50 123 4567",
    patientCountry: "United Arab Emirates",
    preferredLanguage: "Arabic / English",
    treatmentCategory: "Organ Transplant & Hepato-Pancreato-Biliary (HPB)",
    preferredContactTime: "11:00 - 17:00 GST",
    entryPath: "doctor_referred",
    assignedHospitalId: "hosp_medanta",
    assignedDoctorId: "doc_gupta",
    assignedQueue: "Transplant_Tier1",
    assignedCoordinatorName: "Ananya Sharma",
    lastContactAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
    slaTargetMinutes: 60,
    slaExpiresAt: new Date(Date.now() + 28 * 60 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "executive_vip_referral",
    utmMedium: "concierge_dubai_desk",
    utmCampaign: "liver_transplant_mena",

    stage: "consultation",
    caseDecisionStatus: "accepted",
    acceptedAt: new Date("2026-08-24T12:00:00Z").toISOString(),
    acceptedByDoctorId: "doc_gupta",
    acceptedByDoctorName: "Dr. Subhash Gupta",

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Decompensated Cirrhosis secondary to NASH with recurrent ascites, fatigue, and portal hypertension.",
      diagnosis: "End-Stage Liver Disease (MELD-Na Score 24), Candidate for Living Donor Liver Transplant (LDLT).",
      recommendedProcedure: "Living Donor Liver Transplant (LDLT)",
      pastMedicalHistory: "Type 2 Diabetes Mellitus (well-controlled), Hypertension. Living donor evaluated (Son Faris, 28yo, blood group compatible B+).",
      allergies: ["None reported"],
    },

    clinicalWorkspace: {
      treatmentPlan:
        "Patient is an optimal LDLT candidate. Living donor right lobe graft volumetric ratio calculated at 68% standard liver volume. 14 Days planned hospital stay (Private Suite + ICU Isolation). Surgical team led by Dr. Subhash Gupta.",
      expectedStayDays: 14,
      costEstimateUsd: 28500,
      suitabilityDetermination: "suitable",
      submittedAt: new Date("2026-08-24T14:30:00Z").toISOString(),
      submittedByDoctorId: "doc_gupta",
      submittedByDoctorName: "Dr. Subhash Gupta",
      lastUpdatedAt: new Date("2026-08-24T14:30:00Z").toISOString(),
    },

    stageHistory: [
      {
        id: "sh_01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date("2026-08-23T08:30:00Z").toISOString(),
        changedByName: "Executive VIP Desk",
        changedByRole: "public",
      },
      {
        id: "sh_02",
        fromStage: "lead",
        toStage: "contacted",
        changedAt: new Date("2026-08-23T08:48:00Z").toISOString(),
        changedByName: "Ananya Sharma",
        changedByRole: "customer_support",
      },
      {
        id: "sh_03",
        fromStage: "contacted",
        toStage: "documents_collected",
        changedAt: new Date("2026-08-24T10:00:00Z").toISOString(),
        changedByName: "Ananya Sharma",
        changedByRole: "customer_support",
      },
      {
        id: "sh_04",
        fromStage: "documents_collected",
        toStage: "hospital_handover",
        changedAt: new Date("2026-08-24T11:15:00Z").toISOString(),
        changedByName: "Ananya Sharma",
        changedByRole: "customer_support",
      },
      {
        id: "sh_05",
        fromStage: "hospital_handover",
        toStage: "consultation",
        changedAt: new Date("2026-08-24T12:00:00Z").toISOString(),
        changedByName: "Dr. Subhash Gupta",
        changedByRole: "hospital_doctor",
      },
    ],

    csNotes: [
      {
        id: "note_01",
        text: "Patient's son Faris Al-Mansoor is the confirmed living donor. Donor volumetric CT scans reviewed and approved by Medanta transplant committee.",
        createdAt: new Date("2026-08-24T10:30:00Z").toISOString(),
        authorName: "Ananya Sharma",
        authorRole: "customer_support",
      },
      {
        id: "note_02",
        text: "Tele-consultation confirmed for Thursday, Aug 27 at 03:30 PM GST with Dr. Subhash Gupta. Video room link generated. Notified patient via WhatsApp.",
        createdAt: new Date("2026-08-25T11:00:00Z").toISOString(),
        authorName: "Ananya Sharma",
        authorRole: "customer_support",
      },
    ],

    documents: [
      {
        id: "doc_mri_scans",
        title: "Abdominal_MRI_Scans.dicom",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "🟢 Reviewed — Volumetric liver study & donor vascular anatomy cleared by Dr. Subhash Gupta's team.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "Abdominal_MRI_Scans.dicom",
            fileSize: "148.5 MB",
            fileType: "application/dicom",
            uploadedAt: "2026-08-24T10:30:00Z",
            uploadedBy: "Tariq Al-Mansoor",
            csNotes: "High-resolution DICOM slices verified.",
          },
        ],
      },
      {
        id: "doc_blood_report",
        title: "Blood_Work_Report.pdf",
        category: "medical_report",
        status: "incomplete",
        csFeedback: "🟡 Missing Page 2 — Viral Serology & Coagulation Factor V assay missing from scan. Please re-upload.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "Blood_Work_Report.pdf",
            fileSize: "2.4 MB",
            fileType: "application/pdf",
            uploadedAt: "2026-08-25T14:15:00Z",
            uploadedBy: "Tariq Al-Mansoor",
            csNotes: "Page 2 missing viral panel.",
          },
        ],
      },
      {
        id: "doc_passport_copy",
        title: "Passport_Copy_Patient.pdf",
        category: "passport_id",
        status: "reviewed",
        csFeedback: "🟢 Verified — Cryptographically locked for Indian e-Medical Visa processing.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "booking",
        versions: [
          {
            version: 1,
            fileName: "Passport_Copy_Patient.pdf",
            fileSize: "1.8 MB",
            fileType: "application/pdf",
            uploadedAt: "2026-08-25T11:00:00Z",
            uploadedBy: "Tariq Al-Mansoor",
            csNotes: "Passport verified valid until 2031. Locked.",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_01",
        consentType: "privacy_data_processing",
        title: "Privacy & Data Processing",
        description: "Patient granted permission for Vedara Care to store, transmit and process medical telemetry in accordance with HIPAA, GDPR, and Indian DPDP Act 2023.",
        agreed: true,
        timestamp: "2026-08-24T09:15:00Z",
        ipAddress: "185.120.45.10 (Dubai, UAE)",
        version: "v2.1 UK/EU",
        digitalSignature: "Tariq Al-Mansoor (Digital 2FA Token)",
      },
      {
        id: "cst_sharing_01",
        consentType: "hospital_document_sharing",
        title: "Document Sharing with Hospital",
        description: "Explicit permission to transmit encrypted diagnostic scans and medical reports to Dr. Subhash Gupta's surgical evaluation board at Medanta – The Medicity.",
        agreed: true,
        timestamp: "2026-08-24T09:18:00Z",
        ipAddress: "185.120.45.10 (Dubai, UAE)",
        version: "v1.4",
        digitalSignature: "Tariq Al-Mansoor",
      },
      {
        id: "cst_tele_01",
        consentType: "tele_consultation_terms",
        title: "Tele-Consultation Terms",
        description: "Cross-border telemedicine advisory scope, limitations of remote audio/video assessment, and diagnostic recommendations.",
        agreed: false,
        timestamp: "",
        ipAddress: "",
        version: "v2.0",
      },
      {
        id: "cst_payment_terms",
        consentType: "payment_staged_terms",
        title: "Payment & Cancellation Terms",
        description: "Stage-wise escrow release schedule, hospital non-refundable slot cancellation terms, and PCI-DSS compliance policy.",
        agreed: false,
        timestamp: "",
        ipAddress: "",
        version: "v1.0",
      },
    ],

    consultation: {
      id: "tele_gupta_89412",
      scheduledAt: "2026-08-27T15:30:00+04:00",
      durationMinutes: 45,
      doctorName: "Dr. Subhash Gupta",
      doctorSpecialty: "Chief Liver Transplant Surgeon & Chairman",
      doctorHospital: "Medanta – The Medicity / Max Healthcare, Delhi NCR",
      doctorAvatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
      meetingLink: "https://vedaracare.health/teleconsult/ved-live-89412",
      status: "scheduled",
      outcome: "pending",
      outcomeNotes: "Pre-consultation review completed. Living donor right lobe anatomy approved. Ready for patient tele-consult.",
      diagnosticPreChecklist: [
        { item: "Abdominal MRI DICOM Scans loaded in viewer", completed: true },
        { item: "Missing Page 2 of blood work requested from Dubai clinic", completed: false },
        { item: "Donor Faris Al-Mansoor compatibility verified (B+)", completed: true },
      ],
      recordingEnabled: false,
      recordingConsentObtained: false,
      recordingJurisdictionChecked: false,
    },

    quote: {
      id: "qte_89412_tariq",
      quoteNumber: "VED-QT-2026-89412",
      treatmentName: "Living Donor Liver Transplant (LDLT) Comprehensive Surgical Package",
      hospitalName: "Medanta – The Medicity, Delhi NCR",
      doctorName: "Dr. Subhash Gupta",
      city: "Delhi NCR / Gurugram, India",
      totalCostUsd: 28500,
      tier: "premium",
      status: "sent",
      createdAt: new Date("2026-08-25T10:00:00Z").toISOString(),
      validUntil: new Date("2026-09-25T10:00:00Z").toISOString(),
      costBreakdown: {
        hospitalChargesUsd: 8500,
        surgeonAndAnesthesiaUsd: 9000,
        implantsAndMedicationUsd: 5500,
        stayAndIcuUsd: 3500,
        vipConciergeAndLogisticsUsd: 1200,
        companionStayUsd: 800,
        coordinationFeeUsd: 0,
        travelAssistanceUsd: 0,
        supportLayerUsd: 0,
      },
      inclusions: [
        "Hospital Stay: 14 Days (Private Suite + ICU Isolation)",
        "Surgeon & Anesthesia Fees: Included (Led by Dr. Subhash Gupta)",
        "Living Donor Evaluation & Hepatectomy Surgery Included",
        "Concierge Inclusions: 5-Star Executive Apartment for Attendant",
        "Airport VIP Transfer (Roundtrip Luxury Chauffeur at Gate 5)",
        "Dedicated Arabic/English Medical Translator & 24/7 Care Officer",
        "12-Month Post-Transplant Tele-Monitoring & Immunosuppression Titration",
      ],
      exclusions: [
        "International Airfare from Dubai to Delhi (Concierge booking available)",
        "Pre-existing non-transplant chronic medication prior to hospital check-in",
      ],
    },

    payments: [
      {
        id: "deposit",
        name: "Stage 1: Deposit (Coordination)",
        percentage: 10.5,
        amountUsd: 3000,
        currency: "USD",
        dueDate: "Completed",
        status: "completed",
        cancellationTerms: "Refundable up to 72h before visa processing.",
        refundPolicy: "100% refundable upon official visa refusal or withdrawal before visa submission.",
        termsAcceptedAt: "2026-08-24T16:20:00Z",
        paidAt: "2026-08-24T16:20:00Z",
        transactionId: "TXN_ESCROW_884210",
        gatewayReference: "GW_REF_88421",
        receiptNumber: "REC-88421",
        paymentMethod: "card",
        reconciled: true,
      },
      {
        id: "advance",
        name: "Stage 2: Advance (Hospital Booking)",
        percentage: 52.6,
        amountUsd: 15000,
        currency: "USD",
        dueDate: "Upon Package Acceptance",
        status: "pending",
        cancellationTerms: "Non-refundable after hospital suite reservation.",
        refundPolicy: "Funds held in certified healthcare escrow until physical hospital check-in.",
        gatewayReference: "",
        reconciled: false,
      },
      {
        id: "final",
        name: "Stage 3: Final Settlement",
        percentage: 36.9,
        amountUsd: 10500,
        currency: "USD",
        dueDate: "Payable upon hospital check-in",
        status: "pending",
        cancellationTerms: "Payable upon hospital check-in.",
        refundPolicy: "Subject to discharge reconciliation against actual ICU days and medication.",
        gatewayReference: "",
        reconciled: false,
      },
    ],

    itinerary: {
      doctorAppointmentDate: "2026-09-01",
      doctorAppointmentTime: "10:00 AM IST",
      hospitalAddress: "Medanta – The Medicity, CH Bakhtawar Singh Road, Sector 38, Gurugram, Delhi NCR 122001",
      flightDetails: {
        flightNumber: "EK-512 (Emirates)",
        airline: "Emirates Airlines",
        arrivalDate: "2026-08-31",
        arrivalTime: "04:15 AM IST",
        terminal: "Terminal 3, Indira Gandhi International Airport (DEL)",
      },
      hotelDetails: {
        name: "The Oberoi Gurugram (5-Star Executive Suites)",
        address: "443 Udyog Vihar Phase V, Gurugram, Delhi NCR 122016",
        checkIn: "2026-08-31",
        checkOut: "2026-09-18",
        roomType: "5-Star Executive Apartment for Attendant with Kitchenette",
        bookingReference: "OB-MED-89412-UAE",
      },
      airportPickup: {
        driverName: "Rajesh Varma (Private Chauffeur)",
        contactPhone: "+91 98110 55432",
        vehicleType: "Toyota Alphard VIP Executive Van",
        vehicleNumber: "DL 1VB 9022",
        pickupLocation: "Arrivals Gate 5 with 'Vedara Care: Tariq Al-Mansoor' name sign board",
      },
      coordinatorContact: {
        name: "Ananya Sharma",
        phone: "+91 98101 88412",
        whatsapp: "+91 98101 88412",
        email: "ananya.sharma@vedaracare.com",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
      },
      visaDocumentChecklist: {
        country: "United Arab Emirates",
        passportValidityRequired: "Minimum 6 months with 2 blank pages",
        mInvitationLetterReady: true,
        embassySubmissionUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
        requiredItems: [
          {
            id: "m_visa_status",
            name: "e-Medical Visa Status: 🟢 Approved",
            completed: true,
            note: "Official Govt Invitation Letter issued with MEA stamp MEA/MED/2026/089412",
          },
          {
            id: "flight_info",
            name: "Flight Details: EK-512 (Emirates) arriving DEL Aug 31 at 04:15 AM",
            completed: true,
            note: "Confirmed e-ticket linked to concierge transfer protocol",
          },
          {
            id: "chauffeur_info",
            name: "On-Ground Arrival Protocol: Private Chauffeur meeting at Gate 5 with name sign board",
            completed: true,
            note: "Chauffeur Rajesh Varma (+91 98110 55432) assigned",
          },
          {
            id: "attendant_info",
            name: "Attendant Information: 1 Escort permitted under e-Medical Attendant Visa",
            completed: true,
            note: "Companion Faris Al-Mansoor cleared under attendant visa",
          },
        ],
      },
    },

    messages: [
      {
        id: "msg_01",
        senderId: "coord_ananya",
        senderName: "Ananya Sharma (Care Coordinator)",
        senderRole: "cs_coordinator",
        text: "Marhaban Mr. Al-Mansoor! Dr. Subhash Gupta has reviewed your Abdominal MRI scans and confirmed your tele-consultation for Thursday, Aug 27 at 03:30 PM (GST).",
        timestamp: "2026-08-25T11:00:00Z",
        isRead: true,
      },
      {
        id: "msg_02",
        senderId: "coord_ananya",
        senderName: "Ananya Sharma (Care Coordinator)",
        senderRole: "cs_coordinator",
        text: "Please re-upload Page 2 of the Blood Work Report (Viral Serology & INR) so Dr. Gupta has the complete hepatic profile before joining the call.",
        timestamp: "2026-08-25T11:15:00Z",
        isRead: true,
      },
      {
        id: "msg_03",
        senderId: "patient_tariq",
        senderName: "Tariq Al-Mansoor",
        senderRole: "patient",
        text: "Thank you Ananya. I have asked the Dubai clinic to fax the missing serology page. My son Faris will join the video consultation with me.",
        timestamp: "2026-08-25T12:00:00Z",
        isRead: true,
      },
      {
        id: "msg_04",
        senderId: "coord_ananya",
        senderName: "Ananya Sharma (Care Coordinator)",
        senderRole: "cs_coordinator",
        text: "Understood! I have activated the secure video room. Our technical desk will assist you 10 minutes prior to call time.",
        timestamp: "2026-08-26T09:30:00Z",
        isRead: false,
      },
    ],

    recoveryCheckIns: [
      {
        id: "rec_check_01",
        submittedAt: new Date().toISOString(),
        daysPostOp: 0,
        painLevel: 1,
        mobilityStatus: "walking_independently",
        incisionHealing: "clean_dry",
        feverReported: false,
        medicationAdherence: "taking_as_prescribed",
        patientNotes: "Pre-admission baseline recorded. Ready for departure on Aug 31.",
        coordinatorAcknowledged: true,
        coordinatorReply: "Chauffeur Rajesh Varma is scheduled to meet you at Gate 5!",
      },
    ],

    auditLogs: [
      {
        id: "aud_01",
        caseId: "PT-2026-089412",
        action: "LEAD_CREATED",
        actorName: "Executive VIP Desk",
        actorRole: "public",
        timestamp: "2026-08-23T08:30:00Z",
        details: "VIP referral case created from UAE. SLA: 30 min.",
        ipAddress: "185.120.45.10",
      },
      {
        id: "aud_02",
        caseId: "PT-2026-089412",
        action: "CASE_ACCEPTED_BY_HOSPITAL",
        actorName: "Dr. Subhash Gupta",
        actorRole: "hospital_doctor",
        timestamp: "2026-08-24T12:00:00Z",
        details: "Case accepted by Dr. Subhash Gupta. LDLT clinical candidacy confirmed.",
      },
      {
        id: "aud_03",
        caseId: "PT-2026-089412",
        action: "CONSULTATION_SCHEDULED",
        actorName: "Ananya Sharma",
        actorRole: "customer_support",
        timestamp: "2026-08-25T11:00:00Z",
        details: "Video room SDK session scheduled for Thursday, Aug 27 at 03:30 PM GST.",
      },
      {
        id: "aud_04",
        caseId: "PT-2026-089412",
        action: "PAYMENT_PROCESSED_DEPOSIT",
        actorName: "Payment Gateway",
        actorRole: "finance_accounts",
        timestamp: "2026-08-24T16:20:00Z",
        details: "Coordination deposit of $3,000 captured. Receipt #REC-88421 generated.",
      },
    ],
    refundRequests: [],
  },

  {
    id: "PT-2026-004412",
    patientName: "David Miller",
    patientEmail: "david.miller@cardiaccare.us",
    patientPhone: "+1 (555) 349-8812",
    patientCountry: "United States",
    preferredLanguage: "English",
    treatmentCategory: "Cardiology & Transcatheter Valve Replacement (TAVR)",
    preferredContactTime: "14:00 - 18:00 EST",
    entryPath: "doctor_referred",
    assignedHospitalId: "hosp_fortis",
    assignedDoctorId: "doc_seth",
    assignedQueue: "Cardiology_Tier1",
    assignedCoordinatorName: "Aisha Khan",
    lastContactAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    slaTargetMinutes: 45,
    slaExpiresAt: new Date(Date.now() + 75 * 60 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "fortis_us_liaison",
    utmMedium: "concierge_referral",
    utmCampaign: "tavr_north_america",

    stage: "consultation",
    caseDecisionStatus: "accepted",
    acceptedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    acceptedByDoctorId: "doc_seth",
    acceptedByDoctorName: "Dr. Ashok Seth",

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Severe calcific aortic stenosis with peak systolic gradient of 78 mmHg. High surgical risk for open heart surgery, recommended for Transcatheter Aortic Valve Replacement (TAVR).",
      diagnosis: "Severe symptomatic Aortic Stenosis (valve area 0.65 cm2), STS mortality risk 6.2%.",
      recommendedProcedure: "Transfemoral Transcatheter Aortic Valve Implantation (TAVI / TAVR) using Edwards SAPIEN 3 Ultra.",
      pastMedicalHistory: "Prior stroke (2020 with complete recovery), Type 2 Diabetes, Mild CKD (eGFR 55).",
      allergies: ["Sulfa drugs"],
    },

    stageHistory: [
      {
        id: "sh_dm_01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        changedByName: "US Liaison Desk",
        changedByRole: "public",
      },
      {
        id: "sh_dm_02",
        fromStage: "lead",
        toStage: "hospital_handover",
        changedAt: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_dm_03",
        fromStage: "hospital_handover",
        toStage: "consultation",
        changedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        changedByName: "Dr. Ashok Seth",
        changedByRole: "hospital_doctor",
      },
    ],

    csNotes: [
      {
        id: "note_dm_01",
        text: "CT Angiogram of iliofemoral vessels reviewed by Fortis structural heart team. Transfemoral access suitable (bilateral lumen >6.5mm). Tele-consult confirmed for 17:00 IST today.",
        createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
    ],

    documents: [
      {
        id: "doc_tavr_ct",
        title: "TAVR_Protocol_CT_Angiography.pdf",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "🟢 Reviewed — Annular perimeter 76.4mm, annular area 448 mm2. Edwards SAPIEN 26mm recommended.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "TAVR_Protocol_CT_Angiography.pdf",
            fileSize: "14.2 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "David Miller",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_dm",
        consentType: "privacy_data_processing",
        title: "HIPAA & International Medical Data Release",
        description: "Patient granted permission for Fortis Memorial Research Institute to evaluate cardiology telemetry.",
        agreed: true,
        timestamp: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "72.229.28.185 (New York, USA)",
        version: "v2.4",
        digitalSignature: "David Miller",
      },
    ],

    consultation: {
      id: "tele_seth_dm",
      scheduledAt: "Today 17:00 IST",
      durationMinutes: 30,
      doctorName: "Dr. Ashok Seth",
      doctorSpecialty: "Chairman - Interventional Cardiology",
      doctorHospital: "Fortis Memorial Research Institute, Delhi NCR",
      doctorAvatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80",
      meetingLink: "https://vedaracare.health/teleconsult/ved-live-4412",
      status: "scheduled",
      outcome: "pending",
      outcomeNotes: "TAVR valve sizing & transfemoral access discussion with patient & daughter.",
      recordingEnabled: false,
    },

    messages: [
      {
        id: "msg_dm_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Good morning Mr. Miller! Dr. Ashok Seth has reviewed your CT Angio and confirmed our video appointment for 17:00 IST today.",
        timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        isRead: true,
      },
    ],
    payments: [],
    recoveryCheckIns: [],
    auditLogs: [],
    refundRequests: [],
  },

  {
    id: "PT-2026-089415",
    patientName: "John Doe",
    patientEmail: "john.doe@globalhealth.org",
    patientPhone: "+1 (555) 438-9921",
    patientCountry: "United States",
    preferredLanguage: "English",
    treatmentCategory: "Orthopedics & Robotic Joint Replacement",
    preferredContactTime: "10:00 - 14:00 EST",
    entryPath: "hospital_referred",
    referredHospitalId: "hosp_apollo",
    assignedHospitalId: "hosp_apollo",
    assignedDoctorId: "doc_ashok_rajgopal",
    assignedQueue: "Orthopedics_MENA",
    assignedCoordinatorName: "Aisha Khan",
    lastContactAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    slaTargetMinutes: 60,
    slaExpiresAt: new Date(Date.now() + 12 * 60 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "apollo_referral_usa",
    utmMedium: "hospital_direct",

    stage: "quote",
    caseDecisionStatus: "accepted",
    acceptedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    acceptedByDoctorId: "doc_ashok_rajgopal",
    acceptedByDoctorName: "Dr. Ashok Rajgopal",

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Bilateral severe osteoarthritic knee pain with varus deformity, failing conservative therapy.",
      diagnosis: "Grade IV Bilateral Knee Osteoarthritis with cartilage denudation.",
      recommendedProcedure: "Robotic-Assisted Bilateral Total Knee Replacement (Mako System)",
      pastMedicalHistory: "Type 2 Diabetes Mellitus (HbA1c 6.8%), Non-smoker.",
      allergies: ["None known"],
    },

    clinicalWorkspace: {
      treatmentPlan:
        "Bilateral Mako robotic TKR under spinal anesthesia. Pre-op HbA1c must be ≤7.5. Cefazolin prophylaxis. Fast-track rehabilitation starting day 1 post-op.",
      expectedStayDays: 5,
      costEstimateUsd: 7200,
      suitabilityDetermination: "suitable",
      submittedAt: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
      submittedByDoctorId: "doc_ashok_rajgopal",
      submittedByDoctorName: "Dr. Ashok Rajgopal",
      lastUpdatedAt: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
    },

    stageHistory: [
      {
        id: "sh_t01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Apollo Referral Form",
        changedByRole: "public",
      },
      {
        id: "sh_t02",
        fromStage: "lead",
        toStage: "contacted",
        changedAt: new Date(Date.now() - 1.4 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_t03",
        fromStage: "contacted",
        toStage: "documents_collected",
        changedAt: new Date(Date.now() - 1.3 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_t04",
        fromStage: "documents_collected",
        toStage: "hospital_handover",
        changedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_t05",
        fromStage: "hospital_handover",
        toStage: "consultation",
        changedAt: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Dr. Ashok Rajgopal",
        changedByRole: "hospital_doctor",
      },
      {
        id: "sh_t06",
        fromStage: "consultation",
        toStage: "quote",
        changedAt: new Date(Date.now() - 0.2 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
    ],

    csNotes: [
      {
        id: "note_t01",
        text: "Patient prefers Arabic communication. Arranged Arabic interpreter for tele-consult. HbA1c confirmed within range for surgery.",
        createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
    ],

    documents: [
      {
        id: "doc_knee_xray",
        title: "Weight-Bearing Bilateral Knee X-Rays (AP & Lateral)",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "X-Rays clear. Medial compartment collapse noted.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "Tariq_Knee_Bilateral_Xray.pdf",
            fileSize: "5.4 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 1.4 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Tariq Al-Mansoor",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_02",
        consentType: "privacy_data_processing",
        title: "Data Processing & GCC Medical Records Privacy",
        description: "Patient consent for medical file evaluation by Apollo Hospitals Chennai.",
        agreed: true,
        timestamp: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "94.200.12.88 (Dubai, UAE)",
        version: "v2.4",
        digitalSignature: "Tariq Al-Mansoor",
      },
      {
        id: "cst_sharing_02",
        consentType: "hospital_document_sharing",
        title: "Medical Report Sharing with Apollo Joint Institute",
        description: "Shared with Dr. Ashok Rajgopal's clinical team.",
        agreed: true,
        timestamp: new Date(Date.now() - 1.4 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "94.200.12.88 (Dubai, UAE)",
        version: "v1.8",
        digitalSignature: "Tariq Al-Mansoor",
      },
    ],

    consultation: {
      id: "tele_apollo_02",
      scheduledAt: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
      durationMinutes: 30,
      doctorName: "Dr. Ashok Rajgopal",
      doctorSpecialty: "Chairman - Orthopedics & Joint Reconstruction",
      doctorHospital: "Apollo Hospitals, Chennai",
      meetingLink: "https://vedaracare.health/teleconsult/ved-live-4128",
      status: "completed",
      outcome: "suitable",
      outcomeNotes: "Robotic Stryker Mako bilateral knee replacement recommended. Fast-track recovery protocol planned.",
      recordingEnabled: false,
    },

    quote: {
      id: "qte_4128_tariq",
      quoteNumber: "VED-QT-2026-4128",
      treatmentName: "Bilateral Robotic Total Knee Replacement (Stryker Mako) All-Inclusive",
      hospitalName: "Apollo Hospitals",
      doctorName: "Dr. Ashok Rajgopal",
      city: "Chennai, India",
      totalCostUsd: 7200,
      tier: "standard",
      status: "sent",
      createdAt: new Date(Date.now() - 0.2 * 24 * 3600 * 1000).toISOString(),
      validUntil: new Date(Date.now() + 30 * 24 * 3600 * 1000).toISOString(),
      costBreakdown: {
        hospitalChargesUsd: 1800,
        surgeonAndAnesthesiaUsd: 2200,
        implantsAndMedicationUsd: 2200,
        stayAndIcuUsd: 500,
        vipConciergeAndLogisticsUsd: 300,
        companionStayUsd: 200,
        coordinationFeeUsd: 0,
        travelAssistanceUsd: 0,
        supportLayerUsd: 0,
      },
      inclusions: [
        "Stryker Triathlon Titanium Implants (FDA-Approved)",
        "5 Nights Hospital Stay in Private Deluxe Suite",
        "Robotic CT-Scan 3D Joint Mapping & Computer Navigation",
        "Physiotherapy & Rehabilitation Sessions included",
        "Airport VIP pickup & Arabic Translator 24/7",
      ],
      exclusions: ["International flights from Dubai"],
    },

    payments: [
      {
        id: "deposit",
        name: "Stage 1: Commitment Deposit (15%)",
        percentage: 15,
        amountUsd: 1080,
        currency: "USD",
        dueDate: "Immediate",
        status: "pending",
        cancellationTerms: "Secures surgical date and M-Visa invitation dispatch.",
        refundPolicy: "100% refundable on visa refusal.",
        gatewayReference: "",
        reconciled: false,
      },
      {
        id: "advance",
        name: "Stage 2: Advance (60%)",
        percentage: 60,
        amountUsd: 4320,
        currency: "USD",
        dueDate: "7 Days Before Travel",
        status: "pending",
        cancellationTerms: "Implant procurement and operating theater reservation.",
        refundPolicy: "90% refundable up to 72 hrs prior.",
        gatewayReference: "",
        reconciled: false,
      },
      {
        id: "final",
        name: "Stage 3: Final Clearance (25%)",
        percentage: 25,
        amountUsd: 1800,
        currency: "USD",
        dueDate: "On Admission",
        status: "pending",
        cancellationTerms: "Final settlement on hospital check-in.",
        refundPolicy: "Reconciliation against discharge bill.",
        gatewayReference: "",
        reconciled: false,
      },
    ],

    messages: [
      {
        id: "msg_tariq_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "مرحباً سيد طارق! لقد راجع الدكتور أشوك صور الأشعة وأكد ملائمة الجراحة الروبوتية. أرسلت لك عرض السعر الشامل في تبويب العروض.",
        timestamp: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
        isRead: false,
      },
    ],
    recoveryCheckIns: [],
    auditLogs: [
      {
        id: "aud_t01",
        caseId: "PT-2026-004128",
        action: "CASE_ACCEPTED_BY_HOSPITAL",
        actorName: "Dr. Ashok Rajgopal",
        actorRole: "hospital_doctor",
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        details: "Case accepted by Apollo Hospitals. Clinical workspace unlocked.",
      },
    ],
    refundRequests: [],
  },

  {
    id: "PT-2026-009514",
    patientName: "Grace Mwangi",
    patientEmail: "grace.mwangi@healthkenya.org",
    patientPhone: "+254 712 345 678",
    patientCountry: "Kenya",
    preferredLanguage: "English",
    treatmentCategory: "Oncology & CyberKnife Radiosurgery",
    preferredContactTime: "12:00 - 16:00 EAT",
    entryPath: "general_enquiry",
    assignedHospitalId: "hosp_fortis",
    assignedDoctorId: "doc_vinod_raina",
    assignedQueue: "Oncology_EMEA",
    assignedCoordinatorName: "",
    lastContactAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    slaTargetMinutes: 60,
    slaExpiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "google_organic",
    utmMedium: "seo",
    utmCampaign: "cyberknife_africa",

    stage: "lead",
    caseDecisionStatus: "pending_review",

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Newly diagnosed localized pulmonary lesion seeking non-invasive precision radiation.",
      diagnosis: "Early-stage non-small cell lung carcinoma (T1bN0M0).",
      recommendedProcedure: "CyberKnife SBRT / Robotic Stereotactic Radiosurgery",
    },

    stageHistory: [
      {
        id: "sh_g01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date(Date.now() - 0.8 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Public Intake Form",
        changedByRole: "public",
      },
      {
        id: "sh_g02",
        fromStage: "lead",
        toStage: "contacted",
        changedAt: new Date(Date.now() - 0.7 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_g03",
        fromStage: "contacted",
        toStage: "documents_collected",
        changedAt: new Date(Date.now() - 0.3 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
    ],

    csNotes: [
      {
        id: "note_g01",
        text: "PET-CT uploaded but incomplete — missing DICOM slices. Requested patient re-upload coronal series. SLA critical — escalating to oncology team.",
        createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
    ],

    documents: [
      {
        id: "doc_grace_petct",
        title: "Whole Body 18F-FDG PET-CT Scan Report",
        category: "scan_imaging",
        status: "incomplete",
        csFeedback: "We received the summary PDF, but Dr. Raina needs the full DICOM disk slice images or high-resolution coronal series to calculate target volume.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "PET_CT_Nairobi_Hospital_Summary.pdf",
            fileSize: "2.1 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 0.7 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Grace Mwangi",
            csNotes: "Missing coronal and sagittal slices.",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_03",
        consentType: "privacy_data_processing",
        title: "Privacy & Data Protection Agreement",
        description: "Patient consent for oncology file evaluation.",
        agreed: true,
        timestamp: new Date(Date.now() - 0.8 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "197.248.112.5 (Nairobi, Kenya)",
        version: "v2.4",
        digitalSignature: "Grace Mwangi",
      },
    ],

    payments: [],
    messages: [
      {
        id: "msg_grace_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Hello Grace! Our oncology tumor board is reviewing your PET-CT. Please re-upload the DICOM slice images so we can schedule Dr. Raina's consultation tomorrow.",
        timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
        isRead: true,
      },
    ],
    recoveryCheckIns: [],
    auditLogs: [
      {
        id: "aud_g01",
        caseId: "PT-2026-009514",
        action: "LEAD_CREATED",
        actorName: "Public Intake Form",
        actorRole: "public",
        timestamp: new Date(Date.now() - 0.8 * 24 * 3600 * 1000).toISOString(),
        details: "Lead created from Kenya. SLA: 60 min.",
        ipAddress: "197.248.112.5",
      },
    ],
    refundRequests: [],
  },

  // Nurture case — declined by hospital, paused
  {
    id: "PT-2026-007711",
    patientName: "Mei Lin",
    patientEmail: "mei.lin@outlook.cn",
    patientPhone: "+86 138 0013 8000",
    patientCountry: "China",
    preferredLanguage: "Mandarin",
    treatmentCategory: "Neurology & Spine Surgery",
    entryPath: "general_enquiry",
    assignedHospitalId: "hosp_medanta",
    assignedDoctorId: "doc_trehan",
    assignedQueue: "General_Global",
    assignedCoordinatorName: "Aisha Khan",
    lastContactAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    slaTargetMinutes: 45,
    slaExpiresAt: new Date(Date.now() - 9.8 * 24 * 3600 * 1000).toISOString(),
    slaBreached: true,

    utmSource: "baidu_ads",
    utmMedium: "cpc_china",
    utmCampaign: "spine_decompression_cn",

    stage: "nurture",
    caseDecisionStatus: "declined",
    declineReason: "Patient MRI shows multi-level cervical myelopathy requiring anterior cervical corpectomy — outside our TAVR-focused team's scope at this time. Recommending referral to spine specialist at Artemis Hospital.",
    declinedAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Progressive cervical myelopathy with bilateral arm weakness.",
      diagnosis: "Multi-level cervical disc herniation C4-C7 with cord compression.",
      recommendedProcedure: "Anterior Cervical Discectomy & Fusion (ACDF) or Corpectomy",
    },

    nurtureEntry: {
      reason: "declined_by_hospital",
      notes: "Hospital declined — outside specialty scope. Patient interested in pursuing with a spine-focused center. Scheduled follow-up to re-engage.",
      scheduledFollowUpAt: new Date(Date.now() + 7 * 24 * 3600 * 1000).toISOString(),
      addedAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
      addedByName: "Aisha Khan",
    },

    stageHistory: [
      {
        id: "sh_m01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Public Intake Form",
        changedByRole: "public",
      },
      {
        id: "sh_m02",
        fromStage: "lead",
        toStage: "hospital_handover",
        changedAt: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
        reason: "Skipped contacted/docs stage — urgent referral from partner clinic",
      },
      {
        id: "sh_m03",
        fromStage: "hospital_handover",
        toStage: "nurture",
        changedAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
        reason: "Hospital declined case. Moving to nurture for re-engagement with spine specialist.",
      },
    ],

    csNotes: [
      {
        id: "note_m01",
        text: "Hospital (Medanta) declined this case — outside cardiac team scope. Need to find spine specialist. Artemis and Kokilaben shortlisted.",
        createdAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
    ],

    documents: [],
    consents: [
      {
        id: "cst_privacy_m01",
        consentType: "privacy_data_processing",
        title: "Privacy & Data Processing Consent",
        description: "Basic intake consent.",
        agreed: true,
        timestamp: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "183.60.0.1 (Beijing, China)",
        version: "v2.4",
        digitalSignature: "Mei Lin",
      },
    ],
    payments: [],
    messages: [],
    recoveryCheckIns: [],
    auditLogs: [
      {
        id: "aud_m01",
        caseId: "PT-2026-007711",
        action: "CASE_DECLINED_BY_HOSPITAL",
        actorName: "Dr. Naresh Trehan",
        actorRole: "hospital_doctor",
        timestamp: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
        details: "Declined: Outside specialty scope. Reason logged. Case moved to Nurture queue.",
      },
    ],
    refundRequests: [],
  },
];

// ─── Security & MFA Enforcement Logs ──────────────────────────────────────────
export const MOCK_SECURITY_MFA_LOGS: SecurityMfaLog[] = [
  {
    id: "sec_log_01",
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    eventType: "login_success",
    userId: "user_admin_rajesh",
    userName: "Rajesh Verma",
    userRole: "super_admin",
    ipAddress: "14.139.45.12 (New Delhi, India)",
    geoCountry: "India",
    deviceInfo: "macOS 15.2 • Chrome 128.0 Enterprise",
    threatLevel: "normal",
    status: "success",
    details: "Authenticated via Hardware Security Key (FIDO2 WebAuthn). Session token signed.",
  },
  {
    id: "sec_log_02",
    timestamp: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    eventType: "mfa_challenge_failed",
    userId: "user_cs_fatima",
    userName: "Fatima Al-Sayed",
    userRole: "customer_support",
    ipAddress: "86.98.112.4 (Dubai, UAE)",
    geoCountry: "United Arab Emirates",
    deviceInfo: "Windows 11 • Edge 127",
    threatLevel: "medium",
    status: "blocked",
    details: "TOTP code entered exceeded 30s drift window. Secondary challenge issued.",
  },
  {
    id: "sec_log_03",
    timestamp: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    eventType: "mfa_enforced",
    userId: "user_doctor_prathap",
    userName: "Dr. Prathap C. Reddy",
    userRole: "hospital_doctor",
    ipAddress: "182.73.120.90 (Chennai, India)",
    geoCountry: "India",
    deviceInfo: "iPadOS 17.5 • Mobile Safari",
    threatLevel: "normal",
    status: "success",
    details: "Mandatory Doctor MFA policy enforced on clinical record access.",
  },
  {
    id: "sec_log_04",
    timestamp: new Date(Date.now() - 280 * 60 * 1000).toISOString(),
    eventType: "privilege_escalation_attempt",
    userId: "user_patient_elena",
    userName: "Elena Rostova",
    userRole: "patient",
    ipAddress: "185.12.94.22 (London, UK)",
    geoCountry: "United Kingdom",
    deviceInfo: "Firefox 129 • macOS",
    threatLevel: "high",
    status: "blocked",
    details: "Direct URL parameter probe on /api/admin/escrow-vault blocked by RLS filter.",
  },
  {
    id: "sec_log_05",
    timestamp: new Date(Date.now() - 420 * 60 * 1000).toISOString(),
    eventType: "session_revoked",
    userId: "user_finance_sarah",
    userName: "Sarah Jenkins",
    userRole: "finance_accounts",
    ipAddress: "66.249.66.1 (New York, USA)",
    geoCountry: "United States",
    deviceInfo: "Chrome 128 • Windows 11",
    threatLevel: "normal",
    status: "success",
    details: "Session terminated due to 60-minute inactivity security policy.",
  },
  {
    id: "sec_log_06",
    timestamp: new Date(Date.now() - 600 * 60 * 1000).toISOString(),
    eventType: "login_failed",
    userId: "unknown_actor",
    userName: "Unregistered Account",
    userRole: "public",
    ipAddress: "45.154.255.88 (Frankfurt, Germany)",
    geoCountry: "Germany",
    deviceInfo: "Python-urllib/3.11",
    threatLevel: "critical",
    status: "blocked",
    details: "Credential stuffing attempt against /api/auth/v1/token. IP automatically rate-limited (429).",
  },
];

// ─── Hospital Commission & Payout Batches ────────────────────────────────────
export const MOCK_HOSPITAL_PAYOUTS: HospitalPayoutBatch[] = [
  {
    id: "payout_batch_001",
    hospitalId: "hosp_medanta",
    hospitalName: "Medanta – The Medicity",
    caseCount: 8,
    grossAmountUsd: 142000,
    platformFeePercentage: 12,
    platformFeeUsd: 17040,
    netPayoutUsd: 124960,
    bankSwiftCode: "HDFC0000120",
    bankIban: "IN89HDFC0000120000000000000000",
    status: "pending_approval",
    periodStart: "2026-08-01",
    periodEnd: "2026-08-15",
    initiatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "payout_batch_002",
    hospitalId: "hosp_apollo",
    hospitalName: "Apollo Hospitals Greams Road",
    caseCount: 12,
    grossAmountUsd: 198500,
    platformFeePercentage: 12,
    platformFeeUsd: 23820,
    netPayoutUsd: 174680,
    bankSwiftCode: "ICIC0000001",
    bankIban: "IN90ICIC0000001000000000000000",
    status: "processing",
    periodStart: "2026-07-16",
    periodEnd: "2026-07-31",
    initiatedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    approvedByName: "Rajesh Verma",
    approvedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "payout_batch_003",
    hospitalId: "hosp_fortis",
    hospitalName: "Fortis Memorial Research Institute",
    caseCount: 6,
    grossAmountUsd: 94000,
    platformFeePercentage: 10,
    platformFeeUsd: 9400,
    netPayoutUsd: 84600,
    bankSwiftCode: "UTIB0000050",
    bankIban: "IN91UTIB0000050000000000000000",
    status: "disbursed",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-15",
    initiatedAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    approvedByName: "Rajesh Verma",
    approvedAt: new Date(Date.now() - 19 * 24 * 3600 * 1000).toISOString(),
  },
];

// ─── Queue Routing & Automation Rules ─────────────────────────────────────────
export const MOCK_ROUTING_RULES: QueueRoutingRule[] = [
  {
    id: "route_rule_01",
    name: "Cardiology Critical Triage",
    keywords: ["cardiac", "valve", "tavr", "tavi", "bypass", "cabg", "angioplasty", "heart"],
    specialty: "Cardiology & Cardiac Surgery",
    targetQueue: "Cardiology_Tier1",
    priorityLevel: "Critical",
    targetCoordinatorLead: "Aisha Khan",
    autoEscalateMinutes: 15,
    active: true,
  },
  {
    id: "route_rule_02",
    name: "EMEA Oncology Desk",
    keywords: ["cancer", "oncology", "chemotherapy", "cyberknife", "car-t", "radiation", "tumor"],
    specialty: "Medical & Surgical Oncology",
    targetQueue: "Oncology_EMEA",
    priorityLevel: "High",
    targetCoordinatorLead: "Fatima Al-Sayed",
    autoEscalateMinutes: 30,
    active: true,
  },
  {
    id: "route_rule_03",
    name: "MENA Orthopedics & Joint Replacement",
    keywords: ["orthopedic", "joint", "knee", "hip", "spine", "scoliosis", "robotic knee"],
    specialty: "Orthopedic Surgery",
    targetQueue: "Orthopedics_MENA",
    priorityLevel: "Medium",
    targetCoordinatorLead: "Carlos Mendez",
    autoEscalateMinutes: 45,
    active: true,
  },
  {
    id: "route_rule_04",
    name: "Americas High-Value / VIP Intake",
    keywords: ["executive", "vip", "concierge", "private suite", "air ambulance"],
    specialty: "Multi-Specialty VIP Care",
    targetQueue: "Executive_VIP_Queue",
    priorityLevel: "Critical",
    targetCoordinatorLead: "Aisha Khan",
    autoEscalateMinutes: 10,
    active: true,
  },
  {
    id: "route_rule_05",
    name: "Global Catch-All Intake",
    keywords: ["(all other inquiries)"],
    specialty: "General Healthcare Inquiries",
    targetQueue: "General_Global",
    priorityLevel: "Standard",
    targetCoordinatorLead: "Carlos Mendez",
    autoEscalateMinutes: 60,
    active: true,
  },
];
