import {
  PatientCase,
  PortalUser,
  AccreditationProfile,
  ConsentTextVersion,
  VisaChecklistRule,
  RefundCancellationRule,
  SlaThreshold,
  SecurityMfaLog,
  HospitalPayoutBatch,
  QueueRoutingRule,
} from "@/types/portal";

export const MOCK_PORTAL_USERS: PortalUser[] = [
  {
    id: "user_patient_robert",
    name: "Robert Vance",
    email: "robert.vance@gmail.com",
    role: "patient",
    patientId: "PT-2026-008492",
    country: "United States",
    phone: "+1 (555) 234-8921",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    mfaEnforced: false,
    isActive: true,
  },
  {
    id: "user_patient_elena",
    name: "Elena Rostova",
    email: "elena.rostova@gmail.com",
    role: "patient",
    patientId: "PT-2026-009104",
    country: "United Kingdom",
    phone: "+44 7700 900142",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    mfaEnforced: false,
    isActive: true,
  },
  {
    id: "user_patient_tariq",
    name: "Tariq Al-Mansoor",
    email: "tariq.mansoor@alnoor.ae",
    role: "patient",
    patientId: "PT-2026-004128",
    country: "United Arab Emirates",
    phone: "+971 50 123 4567",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    mfaEnforced: false,
    isActive: true,
  },
  {
    id: "user_cs_aisha",
    name: "Aisha Khan",
    email: "aisha.khan@vedaracare.com",
    role: "customer_support",
    assignedQueues: ["Cardiology_Tier1", "Oncology_EMEA", "Orthopedics_MENA", "General_Global"],
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    phone: "+91 98101 23456",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_cs_carlos",
    name: "Carlos Mendez",
    email: "carlos.mendez@vedaracare.com",
    role: "customer_support",
    assignedQueues: ["Americas_Intake", "Orthopedics_MENA", "General_Global"],
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (305) 555-0199",
    country: "United States",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_cs_fatima",
    name: "Fatima Al-Sayed",
    email: "fatima.sayed@vedaracare.com",
    role: "customer_support",
    assignedQueues: ["MENA_Arabic_Desk", "Oncology_EMEA", "Executive_VIP_Queue"],
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    phone: "+971 4 399 2200",
    country: "United Arab Emirates",
    mfaEnforced: false,
    isActive: true,
  },
  {
    id: "user_doctor_trehan",
    name: "Dr. Naresh Trehan",
    email: "dr.trehan@medanta.org",
    role: "hospital_doctor",
    hospitalId: "hosp_medanta",
    doctorId: "doc_trehan",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
    phone: "+91 124 414 1414",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_doctor_seth",
    name: "Dr. Ashok Seth",
    email: "dr.ashok.seth@fortis.org",
    role: "hospital_doctor",
    hospitalId: "hosp_fortis",
    doctorId: "doc_seth",
    avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80",
    phone: "+91 11 4277 6222",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_doctor_prathap",
    name: "Dr. Prathap C. Reddy",
    email: "dr.prathap@apollo.org",
    role: "hospital_doctor",
    hospitalId: "hosp_apollo",
    doctorId: "doc_prathap",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80",
    phone: "+91 44 2829 0200",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_finance_david",
    name: "David Miller",
    email: "finance@vedaracare.com",
    role: "finance_accounts",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    phone: "+44 20 7946 0991",
    country: "United Kingdom",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_finance_sarah",
    name: "Sarah Jenkins",
    email: "sarah.jenkins@vedaracare.com",
    role: "finance_accounts",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (212) 555-0144",
    country: "United States",
    mfaEnforced: true,
    isActive: true,
  },
  {
    id: "user_admin_rajesh",
    name: "Rajesh Verma",
    email: "admin@vedaracare.com",
    role: "super_admin",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    phone: "+91 98110 99887",
    country: "India",
    mfaEnforced: true,
    isActive: true,
  },
];

// ─── Accreditation Profiles ───────────────────────────────────────────────────
export const MOCK_ACCREDITATION_PROFILES: AccreditationProfile[] = [
  {
    hospitalId: "hosp_medanta",
    hospitalName: "Medanta – The Medicity",
    jciStatus: "active",
    jciExpiry: "2027-03-15",
    jciDocumentUrl: "#",
    nabhStatus: "active",
    nabhExpiry: "2026-11-30",
    nabhDocumentUrl: "#",
    lastAuditedAt: "2025-10-12",
    country: "India",
    city: "Gurugram",
    specialties: ["Cardiac Surgery", "Oncology", "Neurology", "Transplant"],
  },
  {
    hospitalId: "hosp_apollo",
    hospitalName: "Apollo Hospitals",
    jciStatus: "active",
    jciExpiry: "2026-08-20",
    jciDocumentUrl: "#",
    nabhStatus: "active",
    nabhExpiry: "2027-01-10",
    nabhDocumentUrl: "#",
    lastAuditedAt: "2025-07-04",
    country: "India",
    city: "Chennai",
    specialties: ["Orthopedics", "Oncology", "Cardiology", "Transplant"],
  },
  {
    hospitalId: "hosp_fortis",
    hospitalName: "Fortis Memorial Research Institute",
    jciStatus: "pending_renewal",
    jciExpiry: "2026-09-30",
    jciDocumentUrl: "#",
    nabhStatus: "active",
    nabhExpiry: "2027-05-22",
    nabhDocumentUrl: "#",
    lastAuditedAt: "2025-08-01",
    country: "India",
    city: "Gurugram",
    specialties: ["Radiosurgery", "Oncology", "Neurosurgery"],
  },
];

// ─── Consent Text Versions ────────────────────────────────────────────────────
export const MOCK_CONSENT_TEXT_VERSIONS: ConsentTextVersion[] = [
  {
    id: "ctv_01",
    consentType: "privacy_data_processing",
    country: "United Kingdom",
    version: "v2.4",
    text: "Full GDPR-compliant data processing consent text for UK patients...",
    uploadedAt: "2026-01-15T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
  {
    id: "ctv_02",
    consentType: "privacy_data_processing",
    country: "United Arab Emirates",
    version: "v2.3",
    text: "GCC-compliant data processing consent for UAE patients...",
    uploadedAt: "2026-02-01T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
  {
    id: "ctv_03",
    consentType: "hospital_document_sharing",
    country: "Global",
    version: "v1.8",
    text: "Hospital document sharing consent text — global default...",
    uploadedAt: "2026-01-20T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
  {
    id: "ctv_04",
    consentType: "tele_consultation_terms",
    country: "Global",
    version: "v2.0",
    text: "Tele-consultation terms and scope limitations...",
    uploadedAt: "2026-03-10T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
  {
    id: "ctv_05",
    consentType: "payment_staged_terms",
    country: "Global",
    version: "v1.2",
    text: "Staged payment and escrow terms and conditions...",
    uploadedAt: "2026-01-15T10:00:00Z",
    uploadedByName: "Rajesh Verma",
    isActive: true,
  },
];

// ─── Visa Checklist Rules ─────────────────────────────────────────────────────
export const MOCK_VISA_CHECKLIST_RULES: VisaChecklistRule[] = [
  {
    id: "vr_uk",
    patientHomeCountry: "United Kingdom",
    requiredDocuments: [
      { name: "Passport (min 6 months validity)", mandatory: true },
      { name: "Hospital invitation letter (M-Visa)", mandatory: true },
      { name: "Bank statement (last 3 months)", mandatory: true },
      { name: "Travel insurance proof", mandatory: false, note: "Recommended" },
    ],
    lastUpdatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "vr_uae",
    patientHomeCountry: "United Arab Emirates",
    requiredDocuments: [
      { name: "Passport (min 6 months validity)", mandatory: true },
      { name: "Hospital invitation letter (M-Visa)", mandatory: true },
      { name: "Emirates ID copy", mandatory: true },
    ],
    lastUpdatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "vr_ke",
    patientHomeCountry: "Kenya",
    requiredDocuments: [
      { name: "Passport (min 6 months validity)", mandatory: true },
      { name: "Hospital invitation letter (M-Visa)", mandatory: true },
      { name: "Medical diagnosis letter from home doctor", mandatory: true },
      { name: "Bank statement (last 6 months)", mandatory: true },
    ],
    lastUpdatedAt: "2026-06-01T00:00:00Z",
  },
];

// ─── Refund / Cancellation Rules ──────────────────────────────────────────────
export const MOCK_REFUND_RULES: RefundCancellationRule[] = [
  {
    id: "rr_deposit_default",
    paymentStage: "deposit",
    description: "Deposit refund — default",
    refundPercentage: 100,
    conditions: "Fully refundable minus $150 processing fee if visa is denied (official embassy proof required). Non-refundable once visa submitted.",
    lastUpdatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "rr_advance_default",
    paymentStage: "advance",
    description: "Advance refund — default",
    refundPercentage: 90,
    conditions: "90% refundable if cancelled more than 72 hours before planned departure. 50% refundable within 72 hours. Non-refundable after hospital admission.",
    lastUpdatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "rr_final_default",
    paymentStage: "final",
    description: "Final payment refund — default",
    refundPercentage: 0,
    conditions: "Non-refundable once procedure commenced. Disputed amounts subject to reconciliation review.",
    lastUpdatedAt: "2026-01-15T00:00:00Z",
  },
];

// ─── SLA Thresholds ───────────────────────────────────────────────────────────
export const MOCK_SLA_THRESHOLDS: SlaThreshold[] = [
  { market: "UK / EU", tier1Minutes: 45, tier2Minutes: 120, escalationMinutes: 240 },
  { market: "GCC / MENA", tier1Minutes: 30, tier2Minutes: 90, escalationMinutes: 180 },
  { market: "Africa / APAC", tier1Minutes: 60, tier2Minutes: 150, escalationMinutes: 300 },
  { market: "North America", tier1Minutes: 45, tier2Minutes: 120, escalationMinutes: 240 },
];

// ─── Patient Cases ────────────────────────────────────────────────────────────
export const INITIAL_PATIENT_CASES: PatientCase[] = [
  {
    id: "PT-2026-008492",
    patientName: "Elena Rostova",
    patientEmail: "elena.rostova@gmail.com",
    patientPhone: "+44 7700 900142",
    patientCountry: "United Kingdom",
    preferredLanguage: "English",
    treatmentCategory: "Cardiology & Cardiac Surgery",
    preferredContactTime: "09:00 - 13:00 GMT",
    entryPath: "general_enquiry",
    assignedHospitalId: "hosp_medanta",
    assignedDoctorId: "doc_trehan",
    assignedQueue: "Cardiology_Tier1",
    assignedCoordinatorName: "Aisha Khan",
    lastContactAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    slaTargetMinutes: 45,
    slaExpiresAt: new Date(Date.now() - 3.8 * 24 * 3600 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "google_search",
    utmMedium: "cpc_uk_cardiac",
    utmCampaign: "tavr_valve_replacement_uk",

    stage: "booking",
    caseDecisionStatus: "accepted",
    acceptedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    acceptedByDoctorId: "doc_trehan",
    acceptedByDoctorName: "Dr. Naresh Trehan",

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Severe aortic stenosis with progressive dyspnea on minimal exertion (NYHA Class III).",
      diagnosis: "Degenerative Calcific Aortic Valve Stenosis; Peak Gradient 68 mmHg.",
      recommendedProcedure: "Transcatheter Aortic Valve Replacement (TAVR / TAVI) or Minimally Invasive AVR",
      pastMedicalHistory: "Hypertension (controlled on Amlodipine 5mg), No prior cardiac surgery.",
      allergies: ["Penicillin"],
    },

    clinicalWorkspace: {
      treatmentPlan:
        "Patient is an optimal TAVR candidate via right transfemoral approach. Edwards SAPIEN 3 Ultra 26mm valve indicated per CT annular sizing (24.5mm). Pre-procedure: dual antiplatelet, dental clearance, pacing wire standby. Post-procedure: 24hr ICU monitoring, step-down ward day 2-4.",
      expectedStayDays: 4,
      costEstimateUsd: 9800,
      suitabilityDetermination: "suitable",
      submittedAt: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
      submittedByDoctorId: "doc_trehan",
      submittedByDoctorName: "Dr. Naresh Trehan",
      lastUpdatedAt: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
    },

    stageHistory: [
      {
        id: "sh_01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Public Intake Form",
        changedByRole: "public",
      },
      {
        id: "sh_02",
        fromStage: "lead",
        toStage: "contacted",
        changedAt: new Date(Date.now() - 3.8 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_03",
        fromStage: "contacted",
        toStage: "documents_collected",
        changedAt: new Date(Date.now() - 3.5 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_04",
        fromStage: "documents_collected",
        toStage: "hospital_handover",
        changedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_05",
        fromStage: "hospital_handover",
        toStage: "consultation",
        changedAt: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Dr. Naresh Trehan",
        changedByRole: "hospital_doctor",
      },
      {
        id: "sh_06",
        fromStage: "consultation",
        toStage: "quote",
        changedAt: new Date(Date.now() - 2.2 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_07",
        fromStage: "quote",
        toStage: "payment",
        changedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_08",
        fromStage: "payment",
        toStage: "booking",
        changedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
    ],

    csNotes: [
      {
        id: "note_01",
        text: "Patient confirmed travel companion (daughter Anna Rostova). Arranged companion visa and hotel companion bed. Patient is anxious — called her for reassurance.",
        createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
      {
        id: "note_02",
        text: "Visa invitation letter dispatched to patient email. Embassy appointment set for Aug 28. Checked Medanta hospital slot still confirmed for Sep 2.",
        createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
    ],

    documents: [
      {
        id: "doc_echo_01",
        title: "2D Echocardiogram & Doppler Report",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "Reviewed by Dr. Trehan's clinical team. Valve area 0.7 cm² confirmed. Patient is suitable candidate.",
        currentVersion: 2,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "Echocardiogram_Initial_NHS_2025.pdf",
            fileSize: "3.2 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
            csNotes: "Initial scan low resolution; requested high-res doppler loops.",
          },
          {
            version: 2,
            fileName: "Echo_Doppler_HighRes_DICOM_Verified.pdf",
            fileSize: "8.7 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
            csNotes: "Excellent clarity. All hemodynamics verified by Senior Cardiologist.",
          },
        ],
      },
      {
        id: "doc_coronary_ct",
        title: "Coronary CT Angiography & Aortic Annulus Sizing",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "Annular dimension measured: 24.5mm. Compatible with 26mm Edwards SAPIEN 3 Ultra valve.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "CT_Aortic_Root_Angio_London.pdf",
            fileSize: "14.1 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
            csNotes: "Verified complete scan with contrast protocol.",
          },
        ],
      },
      {
        id: "doc_passport_elena",
        title: "Patient Passport (Bio Page)",
        category: "passport_id",
        status: "reviewed",
        csFeedback: "Passport valid till Nov 2029. Used for Indian Medical Visa (M-Visa) invitation dispatch.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "booking",
        versions: [
          {
            version: 1,
            fileName: "Elena_Rostova_Passport_Bio.pdf",
            fileSize: "1.4 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
            csNotes: "Verified by Visa concierge team.",
          },
        ],
      },
      {
        id: "doc_blood_profile",
        title: "Comprehensive Metabolic Panel & Coagulation Profile",
        category: "medical_report",
        status: "reviewed",
        currentVersion: 1,
        isRequired: false,
        isCaseScoped: true,
        versions: [
          {
            version: 1,
            fileName: "Blood_Profile_Renal_LFT_INR.pdf",
            fileSize: "1.1 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_01",
        consentType: "privacy_data_processing",
        title: "Data Processing, GDPR & International Health Records Consent",
        description: "Patient granted permission for Vedara Care to store, transmit and process medical telemetry in accordance with HIPAA, GDPR, and Indian Digital Personal Data Protection (DPDP) Act 2023.",
        agreed: true,
        timestamp: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v2.4",
        digitalSignature: "Elena Rostova (Signed via 2FA Token)",
      },
      {
        id: "cst_sharing_01",
        consentType: "hospital_document_sharing",
        title: "Document Sharing with Medanta The Medicity & Clinical Review Board",
        description: "Explicit permission to transmit encrypted diagnostic scans and medical reports to Dr. Naresh Trehan's surgical evaluation board.",
        agreed: true,
        timestamp: new Date(Date.now() - 3.8 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v1.8",
        digitalSignature: "Elena Rostova",
      },
      {
        id: "cst_tele_01",
        consentType: "tele_consultation_terms",
        title: "Cross-Border Tele-Consultation & Clinical Evaluation Terms",
        description: "Acknowledgment of telemedicine advisory scope, limitations of remote audio/video assessment, and diagnostic recommendations.",
        agreed: true,
        timestamp: new Date(Date.now() - 2.8 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v2.0",
        digitalSignature: "Elena Rostova",
      },
      {
        id: "cst_pay_dep_01",
        consentType: "payment_staged_terms",
        title: "Deposit Payment (15%) Refund & Stage Cancellation Terms",
        description: "Accepted terms for $1,470 USD initial deposit. Fully refundable up to 10 days before departure if visa is rejected (official embassy proof required), minus $150 processing fee.",
        agreed: true,
        timestamp: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v1.2",
        digitalSignature: "Elena Rostova (Deposit Verified)",
        paymentStageId: "deposit",
      },
      {
        id: "cst_pay_adv_01",
        consentType: "payment_staged_terms",
        title: "Advance Payment (60%) Pre-Admission Escrow Terms",
        description: "Accepted terms for $5,880 USD advance payment. Funds held in healthcare escrow and released to Medanta upon hospital admission registration.",
        agreed: true,
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v1.2",
        digitalSignature: "Elena Rostova (Advance Verified)",
        paymentStageId: "advance",
      },
    ],

    consultation: {
      id: "tele_medanta_01",
      scheduledAt: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
      durationMinutes: 40,
      doctorName: "Dr. Naresh Trehan",
      doctorSpecialty: "Chief Cardiac Surgeon & Chairman",
      doctorHospital: "Medanta - The Medicity, Gurugram (Delhi NCR)",
      doctorAvatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
      meetingLink: "https://vedaracare.health/teleconsult/ved-live-8492",
      status: "completed",
      outcome: "suitable",
      outcomeNotes:
        "Patient thoroughly reviewed. Candidate is well-suited for high-precision TAVR via right transfemoral approach. Estimated 3-4 days in hospital including 1 day in Step-Down ICU. Recovery prognosis is excellent.",
      prescriptionSummary:
        "Pre-procedure: Maintain Amlodipine 5mg; Aspirin 75mg daily. Pre-admission echo to be repeated in Delhi for calibration.",
      diagnosticPreChecklist: [
        { item: "Recent Renal Function (Serum Creatinine < 1.3 mg/dL)", completed: true },
        { item: "Aortic CT Contrast Sizing protocol completed", completed: true },
        { item: "Dental clearance for occult infection", completed: true },
      ],
      recordingEnabled: false,
      recordingConsentObtained: false,
      recordingJurisdictionChecked: false,
    },

    quote: {
      id: "qte_9821_elena",
      quoteNumber: "VED-QT-2026-8492",
      treatmentName: "Transcatheter Aortic Valve Replacement (TAVR / TAVI) All-Inclusive Package",
      hospitalName: "Medanta - The Medicity",
      doctorName: "Dr. Naresh Trehan",
      city: "Gurugram, Delhi NCR",
      totalCostUsd: 9800,
      tier: "premium",
      status: "accepted",
      createdAt: new Date(Date.now() - 2.2 * 24 * 3600 * 1000).toISOString(),
      validUntil: new Date(Date.now() + 28 * 24 * 3600 * 1000).toISOString(),
      costBreakdown: {
        hospitalChargesUsd: 2200,
        surgeonAndAnesthesiaUsd: 2600,
        implantsAndMedicationUsd: 3200,
        stayAndIcuUsd: 900,
        vipConciergeAndLogisticsUsd: 500,
        companionStayUsd: 400,
        coordinationFeeUsd: 0,
        travelAssistanceUsd: 0,
        supportLayerUsd: 0,
      },
      inclusions: [
        "Edwards SAPIEN 3 Ultra / Evolut PRO+ Bioprosthetic Heart Valve",
        "4 Nights Hospital Stay (1 Night Cardiac ICU + 3 Nights Deluxe Private Room)",
        "Pre-operative diagnostics (Echo, Coronary Angio, Blood work, Chest X-Ray)",
        "Lead Surgeon fee (Dr. Naresh Trehan) & full Anesthesiology team",
        "Roundtrip Airport VIP Chauffeur transfer in Delhi",
        "Dedicated English/Russian medical interpreter & 24/7 care officer",
        "6-month post-discharge tele-consultation & follow-up bundle",
      ],
      exclusions: [
        "International airfare from London (booked separately or via concierge)",
        "Treatment for unrelated pre-existing chronic conditions not disclosed",
      ],
      patientDecisionTimestamp: new Date(Date.now() - 2.1 * 24 * 3600 * 1000).toISOString(),
    },

    payments: [
      {
        id: "deposit",
        name: "Stage 1: Commitment Deposit (15%)",
        percentage: 15,
        amountUsd: 1470,
        currency: "USD",
        dueDate: "Completed",
        status: "completed",
        cancellationTerms:
          "Guarantees hospital surgeon scheduling, slot reservation, and official M-Visa invitation letter dispatch. Fully refundable minus $150 processing fee if visa is denied.",
        refundPolicy: "100% refund upon official embassy refusal receipt.",
        termsAcceptedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        paidAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        transactionId: "TXN_STRIPE_984129480",
        gatewayReference: "GW_REF_84129480",
        receiptNumber: "REC-2026-08492-01",
        paymentMethod: "card",
        reconciled: true,
      },
      {
        id: "advance",
        name: "Stage 2: Pre-Admission Escrow Advance (60%)",
        percentage: 60,
        amountUsd: 5880,
        currency: "USD",
        dueDate: "Completed",
        status: "completed",
        cancellationTerms:
          "Secures valve implant procurement, sterilization protocol, and hospital suite reservation. Held in escrow until physical admission.",
        refundPolicy: "90% refundable up to 72 hours before planned flight departure.",
        termsAcceptedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        paidAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        transactionId: "TXN_STRIPE_984138112",
        gatewayReference: "GW_REF_84138112",
        receiptNumber: "REC-2026-08492-02",
        paymentMethod: "card",
        reconciled: true,
      },
      {
        id: "final",
        name: "Stage 3: Final Hospital Clearance (25%)",
        percentage: 25,
        amountUsd: 2450,
        currency: "USD",
        dueDate: "Upon Admission (Day 1)",
        status: "pending",
        cancellationTerms:
          "Final settlement after clinical admission clearance, bed allocation, and pre-op confirmation.",
        refundPolicy: "Subject to discharge reconciliation against actual consumables.",
        gatewayReference: "",
        reconciled: false,
      },
    ],

    itinerary: {
      doctorAppointmentDate: "2026-09-02",
      doctorAppointmentTime: "10:30 AM IST",
      hospitalAddress: "Medanta The Medicity, Sector 38, Gurugram, Haryana 122001, India",
      flightDetails: {
        flightNumber: "BA 143 (British Airways)",
        airline: "British Airways",
        arrivalDate: "2026-09-01",
        arrivalTime: "08:15 AM IST",
        terminal: "Terminal 3, Indira Gandhi International Airport (DEL)",
      },
      hotelDetails: {
        name: "The Oberoi Gurugram (Luxury Medical Suite Partner)",
        address: "443 Udyog Vihar, Phase V, Gurugram 122016",
        checkIn: "2026-09-01",
        checkOut: "2026-09-08",
        roomType: "Deluxe Accessible Suite with companion king bed",
        bookingReference: "OB-MED-8492-UK",
      },
      airportPickup: {
        driverName: "Sandeep Sharma (Vedara Care Chauffeur)",
        contactPhone: "+91 98110 44219",
        vehicleType: "Toyota Innova Crysta (Wheelchair Accessible)",
        vehicleNumber: "DL 1ZC 7782",
        pickupLocation: "Arrivals Gate 4 - Meeting Point with 'Vedara Care: Elena Rostova' Nameboard",
      },
      coordinatorContact: {
        name: "Aisha Khan",
        phone: "+91 98200 11450",
        whatsapp: "+91 98200 11450",
        email: "aisha.khan@vedaracare.com",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
      },
      visaDocumentChecklist: {
        country: "United Kingdom",
        passportValidityRequired: "Minimum 6 months with 2 blank pages",
        mInvitationLetterReady: true,
        embassySubmissionUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
        requiredItems: [
          {
            id: "m_letter",
            name: "Medanta Official Medical Visa (M-Visa) Invitation Letter",
            completed: true,
            note: "Generated with hospital seal & registration reference VED/MED/2026/8492",
          },
          {
            id: "passport_scan",
            name: "High-resolution passport front & back PDF",
            completed: true,
            note: "Verified matching international aviation standards",
          },
          {
            id: "photo_white_bg",
            name: "Recent passport photo with white background (5cm x 5cm)",
            completed: true,
            note: "Uploaded & accepted",
          },
          {
            id: "attendant_visa",
            name: "Medical Attendant Visa (MX-Visa) for companion",
            completed: true,
            note: "Daughter Anna Rostova registered as authorized medical attendant",
          },
        ],
      },
    },

    messages: [
      {
        id: "msg_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Good morning Elena! I have verified your high-resolution echocardiogram and forwarded it to Dr. Naresh Trehan's desk at Medanta.",
        timestamp: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: "msg_02",
        senderId: "patient_elena",
        senderName: "Elena Rostova",
        senderRole: "patient",
        text: "Thank you so much Aisha. My daughter Anna will be accompanying me. Does the package include her accommodation at the hospital?",
        timestamp: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: "msg_03",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Yes, absolutely! The Deluxe Private room includes a comfortable sofa-bed, daily meal plan, and lounge access for Anna at no extra charge.",
        timestamp: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: "msg_04",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Your M-Visa invitation letter is signed and attached to your itinerary tab. You can download it directly for your Indian e-Visa application!",
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        isRead: false,
      },
    ],

    recoveryCheckIns: [
      {
        id: "rec_check_01",
        submittedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        daysPostOp: 0,
        painLevel: 2,
        mobilityStatus: "walking_independently",
        incisionHealing: "clean_dry",
        feverReported: false,
        medicationAdherence: "taking_as_prescribed",
        patientNotes: "Pre-procedure baseline recorded. Feeling calm and prepared for travel.",
        coordinatorAcknowledged: true,
        coordinatorReply: "Looking forward to receiving you at Delhi Airport on Sept 1st!",
      },
    ],

    auditLogs: [
      {
        id: "aud_01",
        caseId: "PT-2026-008492",
        action: "LEAD_CREATED",
        actorName: "Public Intake Form",
        actorRole: "public",
        timestamp: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        details: "Lead submitted from UK. SLA assigned: 45 min.",
        ipAddress: "86.14.120.45",
      },
      {
        id: "aud_02",
        caseId: "PT-2026-008492",
        action: "CASE_ACCEPTED_BY_HOSPITAL",
        actorName: "Dr. Naresh Trehan",
        actorRole: "hospital_doctor",
        timestamp: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        details: "Case accepted by Medanta. Clinical workspace unlocked.",
      },
      {
        id: "aud_03",
        caseId: "PT-2026-008492",
        action: "CLINICAL_WORKSPACE_SAVED",
        actorName: "Dr. Naresh Trehan",
        actorRole: "hospital_doctor",
        timestamp: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
        details: "Treatment plan, LOS (4 days), cost estimate ($9,800), suitability: SUITABLE. Timestamped to doctor's account.",
      },
      {
        id: "aud_04",
        caseId: "PT-2026-008492",
        action: "CONSULTATION_COMPLETED",
        actorName: "Dr. Naresh Trehan",
        actorRole: "hospital_doctor",
        timestamp: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
        details: "Tele-consultation outcome: SUITABLE. Recording: OFF.",
      },
      {
        id: "aud_05",
        caseId: "PT-2026-008492",
        action: "QUOTE_ACCEPTED",
        actorName: "Elena Rostova",
        actorRole: "patient",
        timestamp: new Date(Date.now() - 2.1 * 24 * 3600 * 1000).toISOString(),
        details: "All-inclusive TAVR quote $9,800 accepted.",
      },
      {
        id: "aud_06",
        caseId: "PT-2026-008492",
        action: "PAYMENT_PROCESSED_ADVANCE",
        actorName: "Payment Gateway",
        actorRole: "finance_accounts",
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        details: "Staged advance of $5,880 captured. Gateway Ref: GW_REF_84138112. Terms accepted.",
      },
    ],

    refundRequests: [],
  },

  {
    id: "PT-2026-004128",
    patientName: "Tariq Al-Mansoor",
    patientEmail: "tariq.mansoor@alnoor.ae",
    patientPhone: "+971 50 123 4567",
    patientCountry: "United Arab Emirates",
    preferredLanguage: "Arabic",
    treatmentCategory: "Orthopedics & Robotic Joint Replacement",
    preferredContactTime: "10:00 - 14:00 GST",
    entryPath: "hospital_referred",
    referredHospitalId: "hosp_apollo",
    assignedHospitalId: "hosp_apollo",
    assignedDoctorId: "doc_ashok_rajgopal",
    assignedQueue: "Orthopedics_MENA",
    assignedCoordinatorName: "Aisha Khan",
    lastContactAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
    slaTargetMinutes: 30,
    slaExpiresAt: new Date(Date.now() - 1.2 * 24 * 3600 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "apollo_referral_dubai",
    utmMedium: "hospital_direct",

    stage: "quote",
    caseDecisionStatus: "accepted",
    acceptedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    acceptedByDoctorId: "doc_ashok_rajgopal",
    acceptedByDoctorName: "Dr. Ashok Rajgopal",

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Bilateral severe osteoarthritic knee pain with varus deformity, failing conservative therapy.",
      diagnosis: "Grade IV Bilateral Knee Osteoarthritis with cartilage denudation.",
      recommendedProcedure: "Robotic-Assisted Bilateral Total Knee Replacement (Mako System)",
      pastMedicalHistory: "Type 2 Diabetes Mellitus (HbA1c 6.8%), Non-smoker.",
      allergies: ["None known"],
    },

    clinicalWorkspace: {
      treatmentPlan:
        "Bilateral Mako robotic TKR under spinal anesthesia. Pre-op HbA1c must be ≤7.5. Cefazolin prophylaxis. Fast-track rehabilitation starting day 1 post-op.",
      expectedStayDays: 5,
      costEstimateUsd: 7200,
      suitabilityDetermination: "suitable",
      submittedAt: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
      submittedByDoctorId: "doc_ashok_rajgopal",
      submittedByDoctorName: "Dr. Ashok Rajgopal",
      lastUpdatedAt: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
    },

    stageHistory: [
      {
        id: "sh_t01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Apollo Referral Form",
        changedByRole: "public",
      },
      {
        id: "sh_t02",
        fromStage: "lead",
        toStage: "contacted",
        changedAt: new Date(Date.now() - 1.4 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_t03",
        fromStage: "contacted",
        toStage: "documents_collected",
        changedAt: new Date(Date.now() - 1.3 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_t04",
        fromStage: "documents_collected",
        toStage: "hospital_handover",
        changedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_t05",
        fromStage: "hospital_handover",
        toStage: "consultation",
        changedAt: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Dr. Ashok Rajgopal",
        changedByRole: "hospital_doctor",
      },
      {
        id: "sh_t06",
        fromStage: "consultation",
        toStage: "quote",
        changedAt: new Date(Date.now() - 0.2 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
    ],

    csNotes: [
      {
        id: "note_t01",
        text: "Patient prefers Arabic communication. Arranged Arabic interpreter for tele-consult. HbA1c confirmed within range for surgery.",
        createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
    ],

    documents: [
      {
        id: "doc_knee_xray",
        title: "Weight-Bearing Bilateral Knee X-Rays (AP & Lateral)",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "X-Rays clear. Medial compartment collapse noted.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "Tariq_Knee_Bilateral_Xray.pdf",
            fileSize: "5.4 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 1.4 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Tariq Al-Mansoor",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_02",
        consentType: "privacy_data_processing",
        title: "Data Processing & GCC Medical Records Privacy",
        description: "Patient consent for medical file evaluation by Apollo Hospitals Chennai.",
        agreed: true,
        timestamp: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "94.200.12.88 (Dubai, UAE)",
        version: "v2.4",
        digitalSignature: "Tariq Al-Mansoor",
      },
      {
        id: "cst_sharing_02",
        consentType: "hospital_document_sharing",
        title: "Medical Report Sharing with Apollo Joint Institute",
        description: "Shared with Dr. Ashok Rajgopal's clinical team.",
        agreed: true,
        timestamp: new Date(Date.now() - 1.4 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "94.200.12.88 (Dubai, UAE)",
        version: "v1.8",
        digitalSignature: "Tariq Al-Mansoor",
      },
    ],

    consultation: {
      id: "tele_apollo_02",
      scheduledAt: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
      durationMinutes: 30,
      doctorName: "Dr. Ashok Rajgopal",
      doctorSpecialty: "Chairman - Orthopedics & Joint Reconstruction",
      doctorHospital: "Apollo Hospitals, Chennai",
      meetingLink: "https://vedaracare.health/teleconsult/ved-live-4128",
      status: "completed",
      outcome: "suitable",
      outcomeNotes: "Robotic Stryker Mako bilateral knee replacement recommended. Fast-track recovery protocol planned.",
      recordingEnabled: false,
    },

    quote: {
      id: "qte_4128_tariq",
      quoteNumber: "VED-QT-2026-4128",
      treatmentName: "Bilateral Robotic Total Knee Replacement (Stryker Mako) All-Inclusive",
      hospitalName: "Apollo Hospitals",
      doctorName: "Dr. Ashok Rajgopal",
      city: "Chennai, India",
      totalCostUsd: 7200,
      tier: "standard",
      status: "sent",
      createdAt: new Date(Date.now() - 0.2 * 24 * 3600 * 1000).toISOString(),
      validUntil: new Date(Date.now() + 30 * 24 * 3600 * 1000).toISOString(),
      costBreakdown: {
        hospitalChargesUsd: 1800,
        surgeonAndAnesthesiaUsd: 2200,
        implantsAndMedicationUsd: 2200,
        stayAndIcuUsd: 500,
        vipConciergeAndLogisticsUsd: 300,
        companionStayUsd: 200,
        coordinationFeeUsd: 0,
        travelAssistanceUsd: 0,
        supportLayerUsd: 0,
      },
      inclusions: [
        "Stryker Triathlon Titanium Implants (FDA-Approved)",
        "5 Nights Hospital Stay in Private Deluxe Suite",
        "Robotic CT-Scan 3D Joint Mapping & Computer Navigation",
        "Physiotherapy & Rehabilitation Sessions included",
        "Airport VIP pickup & Arabic Translator 24/7",
      ],
      exclusions: ["International flights from Dubai"],
    },

    payments: [
      {
        id: "deposit",
        name: "Stage 1: Commitment Deposit (15%)",
        percentage: 15,
        amountUsd: 1080,
        currency: "USD",
        dueDate: "Immediate",
        status: "pending",
        cancellationTerms: "Secures surgical date and M-Visa invitation dispatch.",
        refundPolicy: "100% refundable on visa refusal.",
        gatewayReference: "",
        reconciled: false,
      },
      {
        id: "advance",
        name: "Stage 2: Advance (60%)",
        percentage: 60,
        amountUsd: 4320,
        currency: "USD",
        dueDate: "7 Days Before Travel",
        status: "pending",
        cancellationTerms: "Implant procurement and operating theater reservation.",
        refundPolicy: "90% refundable up to 72 hrs prior.",
        gatewayReference: "",
        reconciled: false,
      },
      {
        id: "final",
        name: "Stage 3: Final Clearance (25%)",
        percentage: 25,
        amountUsd: 1800,
        currency: "USD",
        dueDate: "On Admission",
        status: "pending",
        cancellationTerms: "Final settlement on hospital check-in.",
        refundPolicy: "Reconciliation against discharge bill.",
        gatewayReference: "",
        reconciled: false,
      },
    ],

    messages: [
      {
        id: "msg_tariq_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "مرحباً سيد طارق! لقد راجع الدكتور أشوك صور الأشعة وأكد ملائمة الجراحة الروبوتية. أرسلت لك عرض السعر الشامل في تبويب العروض.",
        timestamp: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
        isRead: false,
      },
    ],
    recoveryCheckIns: [],
    auditLogs: [
      {
        id: "aud_t01",
        caseId: "PT-2026-004128",
        action: "CASE_ACCEPTED_BY_HOSPITAL",
        actorName: "Dr. Ashok Rajgopal",
        actorRole: "hospital_doctor",
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        details: "Case accepted by Apollo Hospitals. Clinical workspace unlocked.",
      },
    ],
    refundRequests: [],
  },

  {
    id: "PT-2026-009514",
    patientName: "Grace Mwangi",
    patientEmail: "grace.mwangi@healthkenya.org",
    patientPhone: "+254 712 345 678",
    patientCountry: "Kenya",
    preferredLanguage: "English",
    treatmentCategory: "Oncology & CyberKnife Radiosurgery",
    preferredContactTime: "12:00 - 16:00 EAT",
    entryPath: "general_enquiry",
    assignedHospitalId: "hosp_fortis",
    assignedDoctorId: "doc_vinod_raina",
    assignedQueue: "Oncology_EMEA",
    assignedCoordinatorName: "Aisha Khan",
    lastContactAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 0.8 * 24 * 3600 * 1000).toISOString(),
    slaTargetMinutes: 60,
    slaExpiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "google_organic",
    utmMedium: "seo",
    utmCampaign: "cyberknife_africa",

    stage: "documents_collected",
    caseDecisionStatus: "pending_review",

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Newly diagnosed localized pulmonary lesion seeking non-invasive precision radiation.",
      diagnosis: "Early-stage non-small cell lung carcinoma (T1bN0M0).",
      recommendedProcedure: "CyberKnife SBRT / Robotic Stereotactic Radiosurgery",
    },

    stageHistory: [
      {
        id: "sh_g01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date(Date.now() - 0.8 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Public Intake Form",
        changedByRole: "public",
      },
      {
        id: "sh_g02",
        fromStage: "lead",
        toStage: "contacted",
        changedAt: new Date(Date.now() - 0.7 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
      {
        id: "sh_g03",
        fromStage: "contacted",
        toStage: "documents_collected",
        changedAt: new Date(Date.now() - 0.3 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
      },
    ],

    csNotes: [
      {
        id: "note_g01",
        text: "PET-CT uploaded but incomplete — missing DICOM slices. Requested patient re-upload coronal series. SLA critical — escalating to oncology team.",
        createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
    ],

    documents: [
      {
        id: "doc_grace_petct",
        title: "Whole Body 18F-FDG PET-CT Scan Report",
        category: "scan_imaging",
        status: "incomplete",
        csFeedback: "We received the summary PDF, but Dr. Raina needs the full DICOM disk slice images or high-resolution coronal series to calculate target volume.",
        currentVersion: 1,
        isRequired: true,
        isCaseScoped: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "PET_CT_Nairobi_Hospital_Summary.pdf",
            fileSize: "2.1 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 0.7 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Grace Mwangi",
            csNotes: "Missing coronal and sagittal slices.",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_03",
        consentType: "privacy_data_processing",
        title: "Privacy & Data Protection Agreement",
        description: "Patient consent for oncology file evaluation.",
        agreed: true,
        timestamp: new Date(Date.now() - 0.8 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "197.248.112.5 (Nairobi, Kenya)",
        version: "v2.4",
        digitalSignature: "Grace Mwangi",
      },
    ],

    payments: [],
    messages: [
      {
        id: "msg_grace_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Hello Grace! Our oncology tumor board is reviewing your PET-CT. Please re-upload the DICOM slice images so we can schedule Dr. Raina's consultation tomorrow.",
        timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
        isRead: true,
      },
    ],
    recoveryCheckIns: [],
    auditLogs: [
      {
        id: "aud_g01",
        caseId: "PT-2026-009514",
        action: "LEAD_CREATED",
        actorName: "Public Intake Form",
        actorRole: "public",
        timestamp: new Date(Date.now() - 0.8 * 24 * 3600 * 1000).toISOString(),
        details: "Lead created from Kenya. SLA: 60 min.",
        ipAddress: "197.248.112.5",
      },
    ],
    refundRequests: [],
  },

  // Nurture case — declined by hospital, paused
  {
    id: "PT-2026-007711",
    patientName: "Mei Lin",
    patientEmail: "mei.lin@outlook.cn",
    patientPhone: "+86 138 0013 8000",
    patientCountry: "China",
    preferredLanguage: "Mandarin",
    treatmentCategory: "Neurology & Spine Surgery",
    entryPath: "general_enquiry",
    assignedHospitalId: "hosp_medanta",
    assignedDoctorId: "doc_trehan",
    assignedQueue: "General_Global",
    assignedCoordinatorName: "Aisha Khan",
    lastContactAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),

    leadCreatedAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    slaTargetMinutes: 45,
    slaExpiresAt: new Date(Date.now() - 9.8 * 24 * 3600 * 1000).toISOString(),
    slaBreached: true,

    utmSource: "baidu_ads",
    utmMedium: "cpc_china",
    utmCampaign: "spine_decompression_cn",

    stage: "nurture",
    caseDecisionStatus: "declined",
    declineReason: "Patient MRI shows multi-level cervical myelopathy requiring anterior cervical corpectomy — outside our TAVR-focused team's scope at this time. Recommending referral to spine specialist at Artemis Hospital.",
    declinedAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),

    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Progressive cervical myelopathy with bilateral arm weakness.",
      diagnosis: "Multi-level cervical disc herniation C4-C7 with cord compression.",
      recommendedProcedure: "Anterior Cervical Discectomy & Fusion (ACDF) or Corpectomy",
    },

    nurtureEntry: {
      reason: "declined_by_hospital",
      notes: "Hospital declined — outside specialty scope. Patient interested in pursuing with a spine-focused center. Scheduled follow-up to re-engage.",
      scheduledFollowUpAt: new Date(Date.now() + 7 * 24 * 3600 * 1000).toISOString(),
      addedAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
      addedByName: "Aisha Khan",
    },

    stageHistory: [
      {
        id: "sh_m01",
        fromStage: null,
        toStage: "lead",
        changedAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Public Intake Form",
        changedByRole: "public",
      },
      {
        id: "sh_m02",
        fromStage: "lead",
        toStage: "hospital_handover",
        changedAt: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
        reason: "Skipped contacted/docs stage — urgent referral from partner clinic",
      },
      {
        id: "sh_m03",
        fromStage: "hospital_handover",
        toStage: "nurture",
        changedAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
        changedByName: "Aisha Khan",
        changedByRole: "customer_support",
        reason: "Hospital declined case. Moving to nurture for re-engagement with spine specialist.",
      },
    ],

    csNotes: [
      {
        id: "note_m01",
        text: "Hospital (Medanta) declined this case — outside cardiac team scope. Need to find spine specialist. Artemis and Kokilaben shortlisted.",
        createdAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
        authorName: "Aisha Khan",
        authorRole: "customer_support",
      },
    ],

    documents: [],
    consents: [
      {
        id: "cst_privacy_m01",
        consentType: "privacy_data_processing",
        title: "Privacy & Data Processing Consent",
        description: "Basic intake consent.",
        agreed: true,
        timestamp: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "183.60.0.1 (Beijing, China)",
        version: "v2.4",
        digitalSignature: "Mei Lin",
      },
    ],
    payments: [],
    messages: [],
    recoveryCheckIns: [],
    auditLogs: [
      {
        id: "aud_m01",
        caseId: "PT-2026-007711",
        action: "CASE_DECLINED_BY_HOSPITAL",
        actorName: "Dr. Naresh Trehan",
        actorRole: "hospital_doctor",
        timestamp: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
        details: "Declined: Outside specialty scope. Reason logged. Case moved to Nurture queue.",
      },
    ],
    refundRequests: [],
  },
];

// ─── Security & MFA Enforcement Logs ──────────────────────────────────────────
export const MOCK_SECURITY_MFA_LOGS: SecurityMfaLog[] = [
  {
    id: "sec_log_01",
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    eventType: "login_success",
    userId: "user_admin_rajesh",
    userName: "Rajesh Verma",
    userRole: "super_admin",
    ipAddress: "14.139.45.12 (New Delhi, India)",
    geoCountry: "India",
    deviceInfo: "macOS 15.2 • Chrome 128.0 Enterprise",
    threatLevel: "normal",
    status: "success",
    details: "Authenticated via Hardware Security Key (FIDO2 WebAuthn). Session token signed.",
  },
  {
    id: "sec_log_02",
    timestamp: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    eventType: "mfa_challenge_failed",
    userId: "user_cs_fatima",
    userName: "Fatima Al-Sayed",
    userRole: "customer_support",
    ipAddress: "86.98.112.4 (Dubai, UAE)",
    geoCountry: "United Arab Emirates",
    deviceInfo: "Windows 11 • Edge 127",
    threatLevel: "medium",
    status: "blocked",
    details: "TOTP code entered exceeded 30s drift window. Secondary challenge issued.",
  },
  {
    id: "sec_log_03",
    timestamp: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    eventType: "mfa_enforced",
    userId: "user_doctor_prathap",
    userName: "Dr. Prathap C. Reddy",
    userRole: "hospital_doctor",
    ipAddress: "182.73.120.90 (Chennai, India)",
    geoCountry: "India",
    deviceInfo: "iPadOS 17.5 • Mobile Safari",
    threatLevel: "normal",
    status: "success",
    details: "Mandatory Doctor MFA policy enforced on clinical record access.",
  },
  {
    id: "sec_log_04",
    timestamp: new Date(Date.now() - 280 * 60 * 1000).toISOString(),
    eventType: "privilege_escalation_attempt",
    userId: "user_patient_elena",
    userName: "Elena Rostova",
    userRole: "patient",
    ipAddress: "185.12.94.22 (London, UK)",
    geoCountry: "United Kingdom",
    deviceInfo: "Firefox 129 • macOS",
    threatLevel: "high",
    status: "blocked",
    details: "Direct URL parameter probe on /api/admin/escrow-vault blocked by RLS filter.",
  },
  {
    id: "sec_log_05",
    timestamp: new Date(Date.now() - 420 * 60 * 1000).toISOString(),
    eventType: "session_revoked",
    userId: "user_finance_sarah",
    userName: "Sarah Jenkins",
    userRole: "finance_accounts",
    ipAddress: "66.249.66.1 (New York, USA)",
    geoCountry: "United States",
    deviceInfo: "Chrome 128 • Windows 11",
    threatLevel: "normal",
    status: "success",
    details: "Session terminated due to 60-minute inactivity security policy.",
  },
  {
    id: "sec_log_06",
    timestamp: new Date(Date.now() - 600 * 60 * 1000).toISOString(),
    eventType: "login_failed",
    userId: "unknown_actor",
    userName: "Unregistered Account",
    userRole: "public",
    ipAddress: "45.154.255.88 (Frankfurt, Germany)",
    geoCountry: "Germany",
    deviceInfo: "Python-urllib/3.11",
    threatLevel: "critical",
    status: "blocked",
    details: "Credential stuffing attempt against /api/auth/v1/token. IP automatically rate-limited (429).",
  },
];

// ─── Hospital Commission & Payout Batches ────────────────────────────────────
export const MOCK_HOSPITAL_PAYOUTS: HospitalPayoutBatch[] = [
  {
    id: "payout_batch_001",
    hospitalId: "hosp_medanta",
    hospitalName: "Medanta – The Medicity",
    caseCount: 8,
    grossAmountUsd: 142000,
    platformFeePercentage: 12,
    platformFeeUsd: 17040,
    netPayoutUsd: 124960,
    bankSwiftCode: "HDFC0000120",
    bankIban: "IN89HDFC0000120000000000000000",
    status: "pending_approval",
    periodStart: "2026-08-01",
    periodEnd: "2026-08-15",
    initiatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "payout_batch_002",
    hospitalId: "hosp_apollo",
    hospitalName: "Apollo Hospitals Greams Road",
    caseCount: 12,
    grossAmountUsd: 198500,
    platformFeePercentage: 12,
    platformFeeUsd: 23820,
    netPayoutUsd: 174680,
    bankSwiftCode: "ICIC0000001",
    bankIban: "IN90ICIC0000001000000000000000",
    status: "processing",
    periodStart: "2026-07-16",
    periodEnd: "2026-07-31",
    initiatedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    approvedByName: "Rajesh Verma",
    approvedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "payout_batch_003",
    hospitalId: "hosp_fortis",
    hospitalName: "Fortis Memorial Research Institute",
    caseCount: 6,
    grossAmountUsd: 94000,
    platformFeePercentage: 10,
    platformFeeUsd: 9400,
    netPayoutUsd: 84600,
    bankSwiftCode: "UTIB0000050",
    bankIban: "IN91UTIB0000050000000000000000",
    status: "disbursed",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-15",
    initiatedAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    approvedByName: "Rajesh Verma",
    approvedAt: new Date(Date.now() - 19 * 24 * 3600 * 1000).toISOString(),
  },
];

// ─── Queue Routing & Automation Rules ─────────────────────────────────────────
export const MOCK_ROUTING_RULES: QueueRoutingRule[] = [
  {
    id: "route_rule_01",
    name: "Cardiology Critical Triage",
    keywords: ["cardiac", "valve", "tavr", "tavi", "bypass", "cabg", "angioplasty", "heart"],
    specialty: "Cardiology & Cardiac Surgery",
    targetQueue: "Cardiology_Tier1",
    priorityLevel: "Critical",
    targetCoordinatorLead: "Aisha Khan",
    autoEscalateMinutes: 15,
    active: true,
  },
  {
    id: "route_rule_02",
    name: "EMEA Oncology Desk",
    keywords: ["cancer", "oncology", "chemotherapy", "cyberknife", "car-t", "radiation", "tumor"],
    specialty: "Medical & Surgical Oncology",
    targetQueue: "Oncology_EMEA",
    priorityLevel: "High",
    targetCoordinatorLead: "Fatima Al-Sayed",
    autoEscalateMinutes: 30,
    active: true,
  },
  {
    id: "route_rule_03",
    name: "MENA Orthopedics & Joint Replacement",
    keywords: ["orthopedic", "joint", "knee", "hip", "spine", "scoliosis", "robotic knee"],
    specialty: "Orthopedic Surgery",
    targetQueue: "Orthopedics_MENA",
    priorityLevel: "Medium",
    targetCoordinatorLead: "Carlos Mendez",
    autoEscalateMinutes: 45,
    active: true,
  },
  {
    id: "route_rule_04",
    name: "Americas High-Value / VIP Intake",
    keywords: ["executive", "vip", "concierge", "private suite", "air ambulance"],
    specialty: "Multi-Specialty VIP Care",
    targetQueue: "Executive_VIP_Queue",
    priorityLevel: "Critical",
    targetCoordinatorLead: "Aisha Khan",
    autoEscalateMinutes: 10,
    active: true,
  },
  {
    id: "route_rule_05",
    name: "Global Catch-All Intake",
    keywords: ["(all other inquiries)"],
    specialty: "General Healthcare Inquiries",
    targetQueue: "General_Global",
    priorityLevel: "Standard",
    targetCoordinatorLead: "Carlos Mendez",
    autoEscalateMinutes: 60,
    active: true,
  },
];
