import { PatientCase, PortalUser } from "@/types/portal";

export const MOCK_PORTAL_USERS: PortalUser[] = [
  {
    id: "user_patient_robert",
    name: "Robert Vance",
    email: "robert.vance@gmail.com",
    role: "patient",
    patientId: "PT-2026-008492",
    country: "United States",
    phone: "+1 (555) 234-8921",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user_patient_elena",
    name: "Elena Rostova",
    email: "elena.rostova@gmail.com",
    role: "patient",
    patientId: "PT-2026-009104",
    country: "United Kingdom",
    phone: "+44 7700 900142",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user_patient_tariq",
    name: "Tariq Al-Mansoor",
    email: "tariq.mansoor@alnoor.ae",
    role: "patient",
    patientId: "PT-2026-004128",
    country: "United Arab Emirates",
    phone: "+971 50 123 4567",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user_cs_aisha",
    name: "Aisha Khan",
    email: "aisha.khan@vedaracare.com",
    role: "customer_support",
    assignedQueues: ["Cardiology_Tier1", "Oncology_EMEA", "Orthopedics_MENA", "General_Global"],
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user_doctor_trehan",
    name: "Dr. Naresh Trehan",
    email: "dr.trehan@medanta.org",
    role: "hospital_doctor",
    hospitalId: "hosp_medanta",
    doctorId: "doc_trehan",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user_finance_david",
    name: "David Miller",
    email: "finance@vedaracare.com",
    role: "finance_accounts",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user_admin_rajesh",
    name: "Rajesh Verma",
    email: "admin@vedaracare.com",
    role: "super_admin",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_PATIENT_CASES: PatientCase[] = [
  {
    id: "PT-2026-008492",
    patientName: "Robert Vance",
    patientEmail: "robert.vance@gmail.com",
    patientPhone: "+1 (555) 234-8921",
    patientCountry: "United States",
    preferredLanguage: "English",
    treatmentCategory: "Cardiology & Cardiac Surgery",
    preferredContactTime: "09:00 - 13:00 EST",
    entryPath: "general_enquiry",
    assignedHospitalId: "hosp_medanta",
    assignedDoctorId: "doc_trehan",
    assignedQueue: "Cardiology_Tier1",
    assignedCoordinatorName: "Sarah Jenkins",

    leadCreatedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    slaTargetMinutes: 45,
    slaExpiresAt: new Date(Date.now() - 3.8 * 24 * 3600 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "google_search",
    utmMedium: "cpc_uk_cardiac",
    utmCampaign: "tavr_valve_replacement_uk",

    stage: "booking",
    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Severe aortic stenosis with progressive dyspnea on minimal exertion (NYHA Class III).",
      diagnosis: "Degenerative Calcific Aortic Valve Stenosis; Peak Gradient 68 mmHg.",
      recommendedProcedure: "Transcatheter Aortic Valve Replacement (TAVR / TAVI) or Minimally Invasive AVR",
      pastMedicalHistory: "Hypertension (controlled on Amlodipine 5mg), No prior cardiac surgery.",
      allergies: ["Penicillin"],
    },

    documents: [
      {
        id: "doc_echo_01",
        title: "2D Echocardiogram & Doppler Report",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "Reviewed by Dr. Trehan’s clinical team. Valve area 0.7 cm² confirmed. Patient is suitable candidate.",
        currentVersion: 2,
        isRequired: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "Echocardiogram_Initial_NHS_2025.pdf",
            fileSize: "3.2 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
            csNotes: "Initial scan low resolution; requested high-res doppler loops.",
          },
          {
            version: 2,
            fileName: "Echo_Doppler_HighRes_DICOM_Verified.pdf",
            fileSize: "8.7 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
            csNotes: "Excellent clarity. All hemodynamics verified by Senior Cardiologist.",
          },
        ],
      },
      {
        id: "doc_coronary_ct",
        title: "Coronary CT Angiography & Aortic Annulus Sizing",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "Annular dimension measured: 24.5mm. Compatible with 26mm Edwards SAPIEN 3 Ultra valve.",
        currentVersion: 1,
        isRequired: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "CT_Aortic_Root_Angio_London.pdf",
            fileSize: "14.1 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
            csNotes: "Verified complete scan with contrast protocol.",
          },
        ],
      },
      {
        id: "doc_passport_elena",
        title: "Patient Passport (Bio Page)",
        category: "passport_id",
        status: "reviewed",
        csFeedback: "Passport valid till Nov 2029. Used for Indian Medical Visa (M-Visa) invitation dispatch.",
        currentVersion: 1,
        isRequired: true,
        requiredForStage: "booking",
        versions: [
          {
            version: 1,
            fileName: "Elena_Rostova_Passport_Bio.pdf",
            fileSize: "1.4 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
            csNotes: "Verified by Visa concierge team.",
          },
        ],
      },
      {
        id: "doc_blood_profile",
        title: "Comprehensive Metabolic Panel & Coagulation Profile",
        category: "medical_report",
        status: "reviewed",
        currentVersion: 1,
        isRequired: false,
        versions: [
          {
            version: 1,
            fileName: "Blood_Profile_Renal_LFT_INR.pdf",
            fileSize: "1.1 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Elena Rostova",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_01",
        consentType: "privacy_data_processing",
        title: "Data Processing, GDPR & International Health Records Consent",
        description: "Patient granted permission for Vedara Care to store, transmit and process medical telemetry in accordance with HIPAA, GDPR, and Indian Digital Personal Data Protection (DPDP) Act 2023.",
        agreed: true,
        timestamp: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v2.4",
        digitalSignature: "Elena Rostova (Signed via 2FA Token)",
      },
      {
        id: "cst_sharing_01",
        consentType: "hospital_document_sharing",
        title: "Document Sharing with Medanta The Medicity & Clinical Review Board",
        description: "Explicit permission to transmit encrypted diagnostic scans and medical reports to Dr. Naresh Trehan’s surgical evaluation board.",
        agreed: true,
        timestamp: new Date(Date.now() - 3.8 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v1.8",
        digitalSignature: "Elena Rostova",
      },
      {
        id: "cst_tele_01",
        consentType: "tele_consultation_terms",
        title: "Cross-Border Tele-Consultation & Clinical Evaluation Terms",
        description: "Acknowledgment of telemedicine advisory scope, limitations of remote audio/video assessment, and diagnostic recommendations.",
        agreed: true,
        timestamp: new Date(Date.now() - 2.8 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v2.0",
        digitalSignature: "Elena Rostova",
      },
      {
        id: "cst_pay_dep_01",
        consentType: "payment_staged_terms",
        title: "Deposit Payment (15%) Refund & Stage Cancellation Terms",
        description: "Accepted terms for $1,470 USD initial deposit. Fully refundable up to 10 days before departure if visa is rejected (official embassy proof required), minus $150 processing fee.",
        agreed: true,
        timestamp: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v1.2",
        digitalSignature: "Elena Rostova (Deposit Verified)",
        paymentStageId: "deposit",
      },
      {
        id: "cst_pay_adv_01",
        consentType: "payment_staged_terms",
        title: "Advance Payment (60%) Pre-Admission Escrow Terms",
        description: "Accepted terms for $5,880 USD advance payment. Funds held in healthcare escrow and released to Medanta upon hospital admission registration.",
        agreed: true,
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "86.14.120.45 (London, UK)",
        version: "v1.2",
        digitalSignature: "Elena Rostova (Advance Verified)",
        paymentStageId: "advance",
      },
    ],

    consultation: {
      id: "tele_medanta_01",
      scheduledAt: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
      durationMinutes: 40,
      doctorName: "Dr. Naresh Trehan",
      doctorSpecialty: "Chief Cardiac Surgeon & Chairman",
      doctorHospital: "Medanta - The Medicity, Gurugram (Delhi NCR)",
      doctorAvatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
      meetingLink: "https://vedaracare.health/teleconsult/ved-live-8492",
      status: "completed",
      outcome: "suitable",
      outcomeNotes: "Patient thoroughly reviewed. Candidate is well-suited for high-precision TAVR via right transfemoral approach. Estimated 3-4 days in hospital including 1 day in Step-Down ICU. Recovery prognosis is excellent.",
      prescriptionSummary: "Pre-procedure: Maintain Amlodipine 5mg; Aspirin 75mg daily. Pre-admission echo to be repeated in Delhi for calibration.",
      diagnosticPreChecklist: [
        { item: "Recent Renal Function (Serum Creatinine < 1.3 mg/dL)", completed: true },
        { item: "Aortic CT Contrast Sizing protocol completed", completed: true },
        { item: "Dental clearance for occult infection", completed: true },
      ],
    },

    quote: {
      id: "qte_9821_elena",
      quoteNumber: "VED-QT-2026-8492",
      treatmentName: "Transcatheter Aortic Valve Replacement (TAVR / TAVI) All-Inclusive Package",
      hospitalName: "Medanta - The Medicity",
      doctorName: "Dr. Naresh Trehan",
      city: "Gurugram, Delhi NCR",
      totalCostUsd: 9800,
      status: "accepted",
      createdAt: new Date(Date.now() - 2.2 * 24 * 3600 * 1000).toISOString(),
      validUntil: new Date(Date.now() + 28 * 24 * 3600 * 1000).toISOString(),
      costBreakdown: {
        hospitalChargesUsd: 2200,
        surgeonAndAnesthesiaUsd: 2600,
        implantsAndMedicationUsd: 3200,
        stayAndIcuUsd: 900,
        vipConciergeAndLogisticsUsd: 500,
        companionStayUsd: 400,
      },
      inclusions: [
        "Edwards SAPIEN 3 Ultra / Evolut PRO+ Bioprosthetic Heart Valve",
        "4 Nights Hospital Stay (1 Night Cardiac ICU + 3 Nights Deluxe Private Room)",
        "Pre-operative diagnostics (Echo, Coronary Angio, Blood work, Chest X-Ray)",
        "Lead Surgeon fee (Dr. Naresh Trehan) & full Anesthesiology team",
        "Roundtrip Airport VIP Chauffeur transfer in Delhi",
        "Dedicated English/Russian medical interpreter & 24/7 care officer",
        "6-month post-discharge tele-consultation & follow-up bundle",
      ],
      exclusions: [
        "International airfare from London (booked separately or via concierge)",
        "Treatment for unrelated pre-existing chronic conditions not disclosed",
      ],
      patientDecisionTimestamp: new Date(Date.now() - 2.1 * 24 * 3600 * 1000).toISOString(),
    },

    payments: [
      {
        id: "deposit",
        name: "Stage 1: Commitment Deposit (15%)",
        percentage: 15,
        amountUsd: 1470,
        dueDate: "Completed",
        status: "completed",
        cancellationTerms: "Guarantees hospital surgeon scheduling, slot reservation, and official M-Visa invitation letter dispatch. Fully refundable minus $150 processing fee if visa is denied.",
        refundPolicy: "100% refund upon official embassy refusal receipt.",
        termsAcceptedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        paidAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        transactionId: "TXN_STRIPE_984129480",
        receiptNumber: "REC-2026-08492-01",
        paymentMethod: "card",
      },
      {
        id: "advance",
        name: "Stage 2: Pre-Admission Escrow Advance (60%)",
        percentage: 60,
        amountUsd: 5880,
        dueDate: "Completed",
        status: "completed",
        cancellationTerms: "Secures valve implant procurement, sterilization protocol, and hospital suite reservation. Held in escrow until physical admission.",
        refundPolicy: "90% refundable up to 72 hours before planned flight departure.",
        termsAcceptedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        paidAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        transactionId: "TXN_STRIPE_984138112",
        receiptNumber: "REC-2026-08492-02",
        paymentMethod: "card",
      },
      {
        id: "final",
        name: "Stage 3: Final Hospital Clearance (25%)",
        percentage: 25,
        amountUsd: 2450,
        dueDate: "Upon Admission (Day 1)",
        status: "pending",
        cancellationTerms: "Final settlement after clinical admission clearance, bed allocation, and pre-op confirmation.",
        refundPolicy: "Subject to discharge reconciliation against actual consumables.",
        termsAcceptedAt: undefined,
      },
    ],

    itinerary: {
      doctorAppointmentDate: "2026-09-02",
      doctorAppointmentTime: "10:30 AM IST",
      hospitalAddress: "Medanta The Medicity, Sector 38, Gurugram, Haryana 122001, India",
      flightDetails: {
        flightNumber: "BA 143 (British Airways)",
        airline: "British Airways",
        arrivalDate: "2026-09-01",
        arrivalTime: "08:15 AM IST",
        terminal: "Terminal 3, Indira Gandhi International Airport (DEL)",
      },
      hotelDetails: {
        name: "The Oberoi Gurugram (Luxury Medical Suite Partner)",
        address: "443 Udyog Vihar, Phase V, Gurugram 122016",
        checkIn: "2026-09-01",
        checkOut: "2026-09-08",
        roomType: "Deluxe Accessible Suite with companion king bed",
        bookingReference: "OB-MED-8492-UK",
      },
      airportPickup: {
        driverName: "Sandeep Sharma (Vedara Care Chauffeur)",
        contactPhone: "+91 98110 44219",
        vehicleType: "Toyota Innova Crysta (Wheelchair Accessible)",
        vehicleNumber: "DL 1ZC 7782",
        pickupLocation: "Arrivals Gate 4 - Meeting Point with 'Vedara Care: Elena Rostova' Nameboard",
      },
      coordinatorContact: {
        name: "Aisha Khan",
        phone: "+91 98200 11450",
        whatsapp: "+91 98200 11450",
        email: "aisha.khan@vedaracare.com",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
      },
      visaDocumentChecklist: {
        country: "United Kingdom",
        passportValidityRequired: "Minimum 6 months with 2 blank pages",
        mInvitationLetterReady: true,
        embassySubmissionUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
        requiredItems: [
          {
            id: "m_letter",
            name: "Medanta Official Medical Visa (M-Visa) Invitation Letter",
            completed: true,
            note: "Generated with hospital seal & registration reference VED/MED/2026/8492",
          },
          {
            id: "passport_scan",
            name: "High-resolution passport front & back PDF",
            completed: true,
            note: "Verified matching international aviation standards",
          },
          {
            id: "photo_white_bg",
            name: "Recent passport photo with white background (5cm x 5cm)",
            completed: true,
            note: "Uploaded & accepted",
          },
          {
            id: "attendant_visa",
            name: "Medical Attendant Visa (MX-Visa) for companion",
            completed: true,
            note: "Daughter Anna Rostova registered as authorized medical attendant",
          },
        ],
      },
    },

    messages: [
      {
        id: "msg_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Good morning Elena! I have verified your high-resolution echocardiogram and forwarded it to Dr. Naresh Trehan’s desk at Medanta.",
        timestamp: "3 days ago",
        isRead: true,
      },
      {
        id: "msg_02",
        senderId: "patient_elena",
        senderName: "Elena Rostova",
        senderRole: "patient",
        text: "Thank you so much Aisha. My daughter Anna will be accompanying me. Does the package include her accommodation at the hospital?",
        timestamp: "3 days ago",
        isRead: true,
      },
      {
        id: "msg_03",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Yes, absolutely! The Deluxe Private room includes a comfortable sofa-bed, daily meal plan, and lounge access for Anna at no extra charge.",
        timestamp: "2 days ago",
        isRead: true,
      },
      {
        id: "msg_04",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Your M-Visa invitation letter is signed and attached to your itinerary tab. You can download it directly for your Indian e-Visa application!",
        timestamp: "Yesterday",
        isRead: false,
      },
    ],

    recoveryCheckIns: [
      {
        id: "rec_check_01",
        submittedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        daysPostOp: 0,
        painLevel: 2,
        mobilityStatus: "walking_independently",
        incisionHealing: "clean_dry",
        feverReported: false,
        medicationAdherence: "taking_as_prescribed",
        patientNotes: "Pre-procedure baseline recorded. Feeling calm and prepared for travel.",
        coordinatorAcknowledged: true,
        coordinatorReply: "Looking forward to receiving you at Delhi Airport on Sept 1st!",
      },
    ],

    auditLogs: [
      {
        id: "aud_01",
        caseId: "PT-2026-008492",
        action: "LEAD_CREATED",
        actorName: "Public Intake Form",
        actorRole: "public",
        timestamp: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        details: "Lead submitted from UK. SLA assigned: 45 min.",
        ipAddress: "86.14.120.45",
      },
      {
        id: "aud_02",
        caseId: "PT-2026-008492",
        action: "DOCUMENTS_REVIEWED",
        actorName: "Aisha Khan",
        actorRole: "customer_support",
        timestamp: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        details: "Echocardiogram v2 approved and handed to Medanta Cardiac board.",
      },
      {
        id: "aud_03",
        caseId: "PT-2026-008492",
        action: "CONSULTATION_COMPLETED",
        actorName: "Dr. Naresh Trehan",
        actorRole: "hospital_doctor",
        timestamp: new Date(Date.now() - 2.5 * 24 * 3600 * 1000).toISOString(),
        details: "Outcome set to SUITABLE for TAVR.",
      },
      {
        id: "aud_04",
        caseId: "PT-2026-008492",
        action: "QUOTE_ACCEPTED",
        actorName: "Elena Rostova",
        actorRole: "patient",
        timestamp: new Date(Date.now() - 2.1 * 24 * 3600 * 1000).toISOString(),
        details: "All-inclusive TAVR quote $9,800 accepted.",
      },
      {
        id: "aud_05",
        caseId: "PT-2026-008492",
        action: "PAYMENT_PROCESSED_ADVANCE",
        actorName: "Payment Gateway",
        actorRole: "finance_accounts",
        timestamp: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        details: "Staged advance of $5,880 captured. Terms accepted.",
      },
    ],
  },
  {
    id: "PT-2026-004128",
    patientName: "Tariq Al-Mansoor",
    patientEmail: "tariq.mansoor@alnoor.ae",
    patientPhone: "+971 50 123 4567",
    patientCountry: "United Arab Emirates",
    preferredLanguage: "Arabic",
    treatmentCategory: "Orthopedics & Robotic Joint Replacement",
    preferredContactTime: "10:00 - 14:00 GST",
    entryPath: "hospital_referred",
    referredHospitalId: "hosp_apollo",
    assignedHospitalId: "hosp_apollo",
    assignedDoctorId: "doc_ashok_rajgopal",
    assignedQueue: "Orthopedics_MENA",
    assignedCoordinatorName: "Aisha Khan",

    leadCreatedAt: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
    slaTargetMinutes: 30,
    slaExpiresAt: new Date(Date.now() - 1.2 * 24 * 3600 * 1000).toISOString(),
    slaBreached: false,

    utmSource: "apollo_referral_dubai",
    utmMedium: "hospital_direct",

    stage: "quote",
    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Bilateral severe osteoarthritic knee pain with varus deformity, failing conservative therapy.",
      diagnosis: "Grade IV Bilateral Knee Osteoarthritis with cartilage denudation.",
      recommendedProcedure: "Robotic-Assisted Bilateral Total Knee Replacement (Mako System)",
      pastMedicalHistory: "Type 2 Diabetes Mellitus (HbA1c 6.8%), Non-smoker.",
      allergies: ["None known"],
    },

    documents: [
      {
        id: "doc_knee_xray",
        title: "Weight-Bearing Bilateral Knee X-Rays (AP & Lateral)",
        category: "scan_imaging",
        status: "reviewed",
        csFeedback: "X-Rays clear. Medial compartment collapse noted.",
        currentVersion: 1,
        isRequired: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "Tariq_Knee_Bilateral_Xray.pdf",
            fileSize: "5.4 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 1.4 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Tariq Al-Mansoor",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_02",
        consentType: "privacy_data_processing",
        title: "Data Processing & GCC Medical Records Privacy",
        description: "Patient consent for medical file evaluation by Apollo Hospitals Chennai.",
        agreed: true,
        timestamp: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "94.200.12.88 (Dubai, UAE)",
        version: "v2.4",
        digitalSignature: "Tariq Al-Mansoor",
      },
      {
        id: "cst_sharing_02",
        consentType: "hospital_document_sharing",
        title: "Medical Report Sharing with Apollo Joint Institute",
        description: "Shared with Dr. Ashok Rajgopal’s clinical team.",
        agreed: true,
        timestamp: new Date(Date.now() - 1.4 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "94.200.12.88 (Dubai, UAE)",
        version: "v1.8",
        digitalSignature: "Tariq Al-Mansoor",
      },
    ],

    consultation: {
      id: "tele_apollo_02",
      scheduledAt: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
      durationMinutes: 30,
      doctorName: "Dr. Ashok Rajgopal",
      doctorSpecialty: "Chairman - Orthopedics & Joint Reconstruction",
      doctorHospital: "Apollo Hospitals, Chennai",
      meetingLink: "https://vedaracare.health/teleconsult/ved-live-4128",
      status: "completed",
      outcome: "suitable",
      outcomeNotes: "Robotic Stryker Mako bilateral knee replacement recommended. Fast-track recovery protocol planned.",
    },

    quote: {
      id: "qte_4128_tariq",
      quoteNumber: "VED-QT-2026-4128",
      treatmentName: "Bilateral Robotic Total Knee Replacement (Stryker Mako) All-Inclusive",
      hospitalName: "Apollo Hospitals",
      doctorName: "Dr. Ashok Rajgopal",
      city: "Chennai, India",
      totalCostUsd: 7200,
      status: "sent",
      createdAt: new Date(Date.now() - 0.2 * 24 * 3600 * 1000).toISOString(),
      validUntil: new Date(Date.now() + 30 * 24 * 3600 * 1000).toISOString(),
      costBreakdown: {
        hospitalChargesUsd: 1800,
        surgeonAndAnesthesiaUsd: 2200,
        implantsAndMedicationUsd: 2200,
        stayAndIcuUsd: 500,
        vipConciergeAndLogisticsUsd: 300,
        companionStayUsd: 200,
      },
      inclusions: [
        "Stryker Triathlon Titanium Implants (FDA-Approved)",
        "5 Nights Hospital Stay in Private Deluxe Suite",
        "Robotic CT-Scan 3D Joint Mapping & Computer Navigation",
        "Physiotherapy & Rehabilitation Sessions included",
        "Airport VIP pickup & Arabic Translator 24/7",
      ],
      exclusions: ["International flights from Dubai"],
    },

    payments: [
      {
        id: "deposit",
        name: "Stage 1: Commitment Deposit (15%)",
        percentage: 15,
        amountUsd: 1080,
        dueDate: "Immediate",
        status: "pending",
        cancellationTerms: "Secures surgical date and M-Visa invitation dispatch.",
        refundPolicy: "100% refundable on visa refusal.",
      },
      {
        id: "advance",
        name: "Stage 2: Advance (60%)",
        percentage: 60,
        amountUsd: 4320,
        dueDate: "7 Days Before Travel",
        status: "pending",
        cancellationTerms: "Implant procurement and operating theater reservation.",
        refundPolicy: "90% refundable up to 72 hrs prior.",
      },
      {
        id: "final",
        name: "Stage 3: Final Clearance (25%)",
        percentage: 25,
        amountUsd: 1800,
        dueDate: "On Admission",
        status: "pending",
        cancellationTerms: "Final settlement on hospital check-in.",
        refundPolicy: "Reconciliation against discharge bill.",
      },
    ],

    messages: [
      {
        id: "msg_tariq_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "مرحباً سيد طارق! لقد راجع الدكتور أشوك صور الأشعة وأكد ملائمة الجراحة الروبوتية. أرسلت لك عرض السعر الشامل في تبويب العروض.",
        timestamp: "5 hours ago",
        isRead: false,
      },
    ],
    recoveryCheckIns: [],
    auditLogs: [],
  },
  {
    id: "PT-2026-009514",
    patientName: "Grace Mwangi",
    patientEmail: "grace.mwangi@healthkenya.org",
    patientPhone: "+254 712 345 678",
    patientCountry: "Kenya",
    preferredLanguage: "English",
    treatmentCategory: "Oncology & CyberKnife Radiosurgery",
    preferredContactTime: "12:00 - 16:00 EAT",
    entryPath: "general_enquiry",
    assignedHospitalId: "hosp_fortis",
    assignedDoctorId: "doc_vinod_raina",
    assignedQueue: "Oncology_EMEA",
    assignedCoordinatorName: "Aisha Khan",

    leadCreatedAt: new Date(Date.now() - 0.8 * 24 * 3600 * 1000).toISOString(),
    slaTargetMinutes: 60,
    slaExpiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(), // 15 min left
    slaBreached: false,

    stage: "documents_collected",
    hasBillingDispute: false,

    clinicalSummary: {
      chiefComplaint: "Newly diagnosed localized pulmonary lesion seeking non-invasive precision radiation.",
      diagnosis: "Early-stage non-small cell lung carcinoma (T1bN0M0).",
      recommendedProcedure: "CyberKnife SBRT / Robotic Stereotactic Radiosurgery",
    },

    documents: [
      {
        id: "doc_grace_petct",
        title: "Whole Body 18F-FDG PET-CT Scan Report",
        category: "scan_imaging",
        status: "incomplete",
        csFeedback: "We received the summary PDF, but Dr. Raina needs the full DICOM disk slice images or high-resolution coronal series to calculate target volume.",
        currentVersion: 1,
        isRequired: true,
        requiredForStage: "documents_collected",
        versions: [
          {
            version: 1,
            fileName: "PET_CT_Nairobi_Hospital_Summary.pdf",
            fileSize: "2.1 MB",
            fileType: "application/pdf",
            uploadedAt: new Date(Date.now() - 0.7 * 24 * 3600 * 1000).toISOString(),
            uploadedBy: "Grace Mwangi",
            csNotes: "Missing coronal and sagittal slices.",
          },
        ],
      },
    ],

    consents: [
      {
        id: "cst_privacy_03",
        consentType: "privacy_data_processing",
        title: "Privacy & Data Protection Agreement",
        description: "Patient consent for oncology file evaluation.",
        agreed: true,
        timestamp: new Date(Date.now() - 0.8 * 24 * 3600 * 1000).toISOString(),
        ipAddress: "197.248.112.5 (Nairobi, Kenya)",
        version: "v2.4",
        digitalSignature: "Grace Mwangi",
      },
    ],

    payments: [],
    messages: [
      {
        id: "msg_grace_01",
        senderId: "coord_aisha",
        senderName: "Aisha Khan (Lead Coordinator)",
        senderRole: "cs_coordinator",
        text: "Hello Grace! Our oncology tumor board is reviewing your PET-CT. Please re-upload the DICOM slice images so we can schedule Dr. Raina's consultation tomorrow.",
        timestamp: "3 hours ago",
        isRead: true,
      },
    ],
    recoveryCheckIns: [],
    auditLogs: [],
  },
];
